package delphos.iu;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import org.hibernate.Query;
import org.hibernate.Session;
import org.jdatepicker.JDateComponentFactory;
import org.jdatepicker.JDatePicker;

import delphos.Documento_Clasificacion;
import delphos.Licitacion_Localizacion;
import delphos.Licitacion_Sector;
import delphos.Patente_Localizacion;
import delphos.Patente_Sector;
import delphos.Tendencia;

public class PanelTendenciasBuscador extends javax.swing.JPanel implements ActionListener, DelphosSelectionListener {

	public static final int PERIODO_ULTIMO_MES = 1;
	public static final int PERIODO_ULTIMOS_3_ANIOS = 2;
	public static final int PERIODO_ULTIMO_ANIO = 3;
	public static final int PERIODO_ULTIMO_SEMESTRE = 4;
	public static final int PERIODO_ULTIMO_TRIMESTRE = 5;
	public static final int PERIODO_USUARIO = 6;

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup bgPublicado;
	private javax.swing.JCheckBox cbLicitaciones;
	private javax.swing.JCheckBox cbPatentes;
	private javax.swing.JCheckBox cbDocs;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JCheckBox jCheckBox5;
	private javax.swing.JCheckBox jCheckBox6;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabelLicitacionTipo;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JRadioButton jrb3UltimosAnios;
	private javax.swing.JRadioButton jrbUltimoAnio;
	private javax.swing.JRadioButton jrbUltimoSemestre;
	private javax.swing.JRadioButton jrbUltimoTrimestre;
	private javax.swing.JRadioButton jrbUltimoMes;
	private javax.swing.JRadioButton jrbEntreFechas;
	protected javax.swing.JButton jbtnBuscar;
	protected javax.swing.JComboBox jcbLicitacionTipo;
	private javax.swing.JTextField jtfDocsAutor;
	private javax.swing.JTextField jtfDocsEntidad;
	private javax.swing.JTextField jtfLicitacionEntidadSolicitante;
	protected JDatePicker dpFechaDesde;
	protected JDatePicker dpFechaHasta;
	private javax.swing.JTextField jtfPatentesSolicitante;
	private javax.swing.JTextField jtfPatentesInventor;
	private javax.swing.JTextField jtfTerminoPrincipal;
	private javax.swing.JPanel panelLicitaciones;
	protected DelphosSelectionTreeDialog<Licitacion_Sector> dstdLicitacionSector;
	protected DelphosSelectionTreeDialog<Licitacion_Localizacion> dstdLicitacionLocalizacion;
	protected DelphosSelectionListDialog<Patente_Localizacion> dsldPatenteLocalizacion;
	protected DelphosSelectionTreeDialog<Patente_Sector> dstdPatenteSector;
	protected DelphosSelectionTreeDialog<Documento_Clasificacion> dstdDocumentoClasificacion;
	protected JButton btnLicitacionSectores;
	protected JButton btnLicitacionLocalizacion;
	protected JButton btnPatenteLocalizacion;
	protected JButton btnPatenteSectores;
	protected JButton btnDocumentoClasificacion;
	protected JLabel lblLicitacionSectores;
	protected JLabel lblLicitacionLocalizacion;
	protected JLabel lblPatenteLocalizacion;
	protected JLabel lblPatenteSectores;
	protected JLabel lblDocumentoClasificacion;
	protected Set<Licitacion_Sector> licitacionSectores = new HashSet<>();
	protected Set<Patente_Localizacion> patenteLocalizacion = new HashSet<>();
	protected Set<Licitacion_Localizacion> licitacionLocalizacion = new HashSet<>();
	protected Set<Patente_Sector> patenteSectores = new HashSet<>();
	protected Set<Patente_Sector> documentoClasificacion = new HashSet<>();

	private PanelTendencias panelPadre;
	// End of variables declaration

	/**
	 * Creates new form PanelTendencias
	 */
	public PanelTendenciasBuscador(PanelTendencias panelPadre) {
		this.panelPadre = panelPadre;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		bgPublicado = new javax.swing.ButtonGroup();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jtfTerminoPrincipal = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jrb3UltimosAnios = new javax.swing.JRadioButton();
		jrbUltimoAnio = new javax.swing.JRadioButton();
		jrbUltimoSemestre = new javax.swing.JRadioButton();
		jrbUltimoTrimestre = new javax.swing.JRadioButton();
		jrbUltimoMes = new javax.swing.JRadioButton();
		jrbEntreFechas = new javax.swing.JRadioButton();
		this.dpFechaDesde = new JDateComponentFactory().createJDatePicker();
		this.dpFechaDesde.setTextEditable(true);
		this.dpFechaDesde.setShowYearButtons(true);
		this.dpFechaDesde.getModel().setValue(null);
		jLabel5 = new javax.swing.JLabel();
		this.dpFechaHasta = new JDateComponentFactory().createJDatePicker();
		this.dpFechaHasta.setTextEditable(true);
		this.dpFechaHasta.setShowYearButtons(true);
		this.dpFechaHasta.getModel().setValue(null);
		panelLicitaciones = new javax.swing.JPanel();
		cbLicitaciones = new javax.swing.JCheckBox();
		btnLicitacionSectores = new javax.swing.JButton();
		lblLicitacionSectores = new javax.swing.JLabel();
		btnLicitacionLocalizacion = new javax.swing.JButton();
		lblLicitacionLocalizacion = new javax.swing.JLabel();

		jLabelLicitacionTipo = new javax.swing.JLabel();
		jcbLicitacionTipo = new javax.swing.JComboBox();

		jLabel8 = new javax.swing.JLabel();
		jtfLicitacionEntidadSolicitante = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		cbPatentes = new javax.swing.JCheckBox();
		btnPatenteSectores = new javax.swing.JButton();
		lblPatenteSectores = new javax.swing.JLabel();
		btnPatenteLocalizacion = new javax.swing.JButton();
		lblPatenteLocalizacion = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jtfPatentesInventor = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jtfPatentesSolicitante = new javax.swing.JTextField();
		lblDocumentoClasificacion = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		cbDocs = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jCheckBox5 = new javax.swing.JCheckBox();
		jCheckBox6 = new javax.swing.JCheckBox();
		btnDocumentoClasificacion = new javax.swing.JButton();
		jLabel15 = new javax.swing.JLabel();
		jtfDocsAutor = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jtfDocsEntidad = new javax.swing.JTextField();
		jbtnBuscar = new javax.swing.JButton();
		jbtnBuscar.addActionListener(this);

		dstdLicitacionSector = new DelphosSelectionTreeDialog<Licitacion_Sector>(Licitacion_Sector.class, this);
		dstdLicitacionLocalizacion = new DelphosSelectionTreeDialog<Licitacion_Localizacion>(Licitacion_Localizacion.class, this);
		dstdPatenteSector = new DelphosSelectionTreeDialog<Patente_Sector>(Patente_Sector.class, this);
		dsldPatenteLocalizacion = new DelphosSelectionListDialog<Patente_Localizacion>(Patente_Localizacion.class, this);
		dstdDocumentoClasificacion = new DelphosSelectionTreeDialog<Documento_Clasificacion>(Documento_Clasificacion.class, this);

		jLabel2.setBackground(new java.awt.Color(153, 153, 153));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		// jLabel2.setText("Buscador de Tendencias");
		jLabel2.setOpaque(true);

		jLabel3.setText("Buscar: ");

		jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jLabel4.setText("Publicado:");

		bgPublicado.add(jrb3UltimosAnios);
		jrb3UltimosAnios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jrb3UltimosAnios.setText("Los últimos 3 años");
		jrb3UltimosAnios.addActionListener(this);
		bgPublicado.add(jrbUltimoAnio);
		jrbUltimoAnio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jrbUltimoAnio.setText("El último año");

		bgPublicado.add(jrbUltimoSemestre);
		jrbUltimoSemestre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jrbUltimoSemestre.setText("El último semestre");

		bgPublicado.add(jrbUltimoTrimestre);
		jrbUltimoTrimestre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jrbUltimoTrimestre.setText("El último trimestre");

		bgPublicado.add(jrbUltimoMes);
		jrbUltimoMes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jrbUltimoMes.setText("El último mes");
		jrbUltimoMes.setSelected(true);

		bgPublicado.add(jrbEntreFechas);
		jrbEntreFechas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jrbEntreFechas.setText("Entre");

		jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jLabel5.setText("y");

		panelLicitaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		cbLicitaciones.setText("LICITACIONES");

		btnLicitacionSectores.setText("Sectores:");
		btnLicitacionSectores.addActionListener(this);
		this.lblLicitacionSectores.setFont(new Font("Dialog", Font.PLAIN, 12));
		this.lblLicitacionSectores.setBackground(Color.WHITE);
		this.lblLicitacionSectores.setOpaque(true);
		this.lblLicitacionSectores.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.LIGHT_GRAY), BorderFactory.createEmptyBorder(3, 5, 3, 5)));
		this.lblLicitacionSectores.setText("Todos");

		btnLicitacionLocalizacion.setText("País:");
		btnLicitacionLocalizacion.addActionListener(this);
		this.lblLicitacionLocalizacion.setFont(new Font("Dialog", Font.PLAIN, 12));
		this.lblLicitacionLocalizacion.setBackground(Color.WHITE);
		this.lblLicitacionLocalizacion.setOpaque(true);
		this.lblLicitacionLocalizacion.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.LIGHT_GRAY), BorderFactory.createEmptyBorder(3, 5, 3, 5)));
		this.lblLicitacionLocalizacion.setText("Todos");

		jcbLicitacionTipo.setModel(this.getListaTipoLicitacion());
		jLabelLicitacionTipo.setText("Tipo:");
		jLabel8.setText("Entidad Emisora:");

		javax.swing.GroupLayout panelLicitacionesLayout = new javax.swing.GroupLayout(panelLicitaciones);
		panelLicitaciones.setLayout(panelLicitacionesLayout);
		panelLicitacionesLayout.setHorizontalGroup(panelLicitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelLicitacionesLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelLicitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelLicitacionesLayout.createSequentialGroup().addComponent(btnLicitacionSectores).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblLicitacionSectores, 0, 167, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnLicitacionLocalizacion).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lblLicitacionLocalizacion, 0, 167, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelLicitacionTipo).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jcbLicitacionTipo, 0, 121, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtfLicitacionEntidadSolicitante))
				.addGroup(panelLicitacionesLayout.createSequentialGroup().addComponent(cbLicitaciones).addGap(0, 0, Short.MAX_VALUE))).addContainerGap()));
		panelLicitacionesLayout.setVerticalGroup(panelLicitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelLicitacionesLayout.createSequentialGroup().addContainerGap().addComponent(cbLicitaciones)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(panelLicitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblLicitacionSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnLicitacionLocalizacion).addComponent(lblLicitacionLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLicitacionSectores).addComponent(jLabelLicitacionTipo).addComponent(jcbLicitacionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel8).addComponent(jtfLicitacionEntidadSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		cbPatentes.setText("PATENTES");

		btnPatenteSectores.setText("Sectores:");
		btnPatenteSectores.addActionListener(this);
		this.lblPatenteSectores.setFont(new Font("Dialog", Font.PLAIN, 12));
		this.lblPatenteSectores.setBackground(Color.WHITE);
		this.lblPatenteSectores.setOpaque(true);
		this.lblPatenteSectores.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.LIGHT_GRAY), BorderFactory.createEmptyBorder(3, 5, 3, 5)));
		this.lblPatenteSectores.setText("Todos");

		btnPatenteLocalizacion.setText("País:");
		btnPatenteLocalizacion.addActionListener(this);
		this.lblPatenteLocalizacion.setFont(new Font("Dialog", Font.PLAIN, 12));
		this.lblPatenteLocalizacion.setBackground(Color.WHITE);
		this.lblPatenteLocalizacion.setOpaque(true);
		this.lblPatenteLocalizacion.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.LIGHT_GRAY), BorderFactory.createEmptyBorder(3, 5, 3, 5)));
		this.lblPatenteLocalizacion.setText("Todos");

		jLabel11.setText("Inventor:");

		jLabel12.setText("Solicitante:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cbPatentes).addGroup(jPanel1Layout.createSequentialGroup().addComponent(btnPatenteSectores).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblPatenteSectores, 0, 167, Short.MAX_VALUE))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnPatenteLocalizacion).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblPatenteLocalizacion, 0, 167, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel11).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtfPatentesInventor).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel12)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtfPatentesSolicitante).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(cbPatentes).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnPatenteSectores).addComponent(lblPatenteSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnPatenteLocalizacion)
						.addComponent(lblPatenteLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel11).addComponent(jtfPatentesInventor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel12).addComponent(jtfPatentesSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		cbDocs.setText("DOCUMENTOS ACADÉMICOS");

		jCheckBox4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jCheckBox4.setText("Tesis");

		jCheckBox5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jCheckBox5.setText("Artículos");
		jCheckBox5.addActionListener(this);

		jCheckBox6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		jCheckBox6.setText("Congresos");
		jCheckBox6.addActionListener(this);
		
		btnDocumentoClasificacion.setText("Clasificación:");
		btnDocumentoClasificacion.addActionListener(this);
		this.lblDocumentoClasificacion.setFont(new Font("Dialog", Font.PLAIN, 12));
		this.lblDocumentoClasificacion.setBackground(Color.WHITE);
		this.lblDocumentoClasificacion.setOpaque(true);
		this.lblDocumentoClasificacion.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.LIGHT_GRAY), BorderFactory.createEmptyBorder(3, 5, 3, 5)));
		this.lblDocumentoClasificacion.setText("Todos");

		jLabel15.setText("Autor:");

		jLabel16.setText("Entidad:");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addComponent(btnDocumentoClasificacion).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblDocumentoClasificacion, 0, 121, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
								.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cbDocs).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jCheckBox4).addGap(18, 18, 18).addComponent(jCheckBox5).addGap(18, 18, 18).addComponent(jCheckBox6))).addGap(0, 0, Short.MAX_VALUE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel15).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtfDocsAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel16).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jtfDocsEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(cbDocs).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jCheckBox4).addComponent(jCheckBox5).addComponent(jCheckBox6))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnDocumentoClasificacion).addComponent(lblDocumentoClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel15)
						.addComponent(jtfDocsAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel16).addComponent(jtfDocsEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jbtnBuscar.setText("Buscar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtfTerminoPrincipal))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel4).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addGroup(layout.createSequentialGroup().addComponent(jrbEntreFechas).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent((JComponent) dpFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
														.addComponent(jrb3UltimosAnios))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent((JComponent) dpFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(layout.createSequentialGroup().addComponent(jrbUltimoAnio).addGap(18, 18, 18).addComponent(jrbUltimoSemestre).addGap(18, 18, 18).addComponent(jrbUltimoTrimestre).addGap(18, 18, 18).addComponent(jrbUltimoMes)))
												.addGap(0, 0, Short.MAX_VALUE))
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(panelLicitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jbtnBuscar)))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(jtfTerminoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(jrb3UltimosAnios).addComponent(jrbUltimoAnio).addComponent(jrbUltimoSemestre).addComponent(jrbUltimoTrimestre).addComponent(jrbUltimoMes)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jrbEntreFechas).addComponent(jLabel5).addComponent((JComponent) dpFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent((JComponent) dpFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18)
						.addComponent(panelLicitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jbtnBuscar)));
	}// </editor-fold>

	public void actionPerformed(ActionEvent e) {
		System.out.println("PanelTendenciasBuscador - ActionListener" + e.getSource());
		this.panelPadre.framePrincipal.frame.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

		if (e.getSource() == jbtnBuscar) {
			System.out.println("Buscando Tendencias de forma inmediata");

			// Validación
			if (!this.cbLicitaciones.isSelected())
				if (!this.cbPatentes.isSelected())
					if (!this.cbDocs.isSelected()){
						JOptionPane.showMessageDialog(this, "Debe seleccionar Licitaciones, Patentes y/o Documentos", "Error", JOptionPane.ERROR_MESSAGE);
						return;
					}

			Tendencia tendencia = new Tendencia();
			tendencia.setTerminoPrincipal(jtfTerminoPrincipal.getText());
			tendencia.setIndicadorLicitaciones(cbLicitaciones.isSelected());
			if (cbLicitaciones.isSelected()) {
				tendencia.setListaLicitacionSector(dstdLicitacionSector.getSeleccion());
				tendencia.setListaLicitacionLocalizacion(dstdLicitacionLocalizacion.getSeleccion());
				tendencia.setLicitacionTipo((String) jcbLicitacionTipo.getSelectedItem());
				tendencia.setLicitacionEntidadSolicitante(jtfLicitacionEntidadSolicitante.getText());
			}
			tendencia.setIndicadorPatentes(cbPatentes.isSelected());
			if (cbPatentes.isSelected()) {
				tendencia.setListaPatenteSector(dstdPatenteSector.getSeleccion());
				tendencia.setListaPatenteLocalizacion(dsldPatenteLocalizacion.getSeleccion());
				tendencia.setPatenteInventor(jtfPatentesInventor.getText());
				tendencia.setPatenteSolicitante(jtfPatentesSolicitante.getText());
			}
			tendencia.setIndicadorDocs(cbDocs.isSelected());
			if (cbDocs.isSelected()) {
				tendencia.setListaDocumentoClasificacion(dstdDocumentoClasificacion.getSeleccion());
				tendencia.setDocumentoAutor(jtfDocsAutor.getText());
				tendencia.setDocumentoEntidad(jtfDocsEntidad.getText());
			}
			int periodo = 0;

			Calendar fechaInicio = Calendar.getInstance();
			Calendar fechaFin = Calendar.getInstance();
			
			String sPeriodo = "";
			if (jrbUltimoMes.isSelected()) {
				periodo = PERIODO_ULTIMO_MES;
				sPeriodo = "Último mes";
				fechaInicio.add(Calendar.MONTH, -1);
			}
			if (jrb3UltimosAnios.isSelected()) {
				periodo = PERIODO_ULTIMOS_3_ANIOS;
				sPeriodo = "Últimos 3 años";
				fechaInicio.add(Calendar.YEAR, -3);
			}
			if (jrbUltimoAnio.isSelected()) {
				periodo = PERIODO_ULTIMO_ANIO;
				sPeriodo = "Último año";
				fechaInicio.add(Calendar.YEAR, -1);
			}
			if (jrbUltimoSemestre.isSelected()) {
				periodo = PERIODO_ULTIMO_SEMESTRE;
				sPeriodo = "Último semestre";
				fechaInicio.add(Calendar.MONTH, -6);
			}
			if (jrbUltimoTrimestre.isSelected()) {
				periodo = PERIODO_ULTIMO_TRIMESTRE;
				sPeriodo = "Último trimestre";
				fechaInicio.add(Calendar.MONTH, -3);
			}
			if (jrbEntreFechas.isSelected()) {
				periodo = PERIODO_USUARIO;
				SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
				fechaInicio = (GregorianCalendar) this.dpFechaDesde.getModel().getValue();
				fechaFin = (GregorianCalendar)this.dpFechaHasta.getModel().getValue();
				sPeriodo = sdf.format(((GregorianCalendar) this.dpFechaDesde.getModel().getValue()).getTime()) + " - " + sdf.format(((GregorianCalendar) this.dpFechaHasta.getModel().getValue()).getTime());
			}

			tendencia.establecerFiltrosPrincipales();
			if (tendencia.getFiltroPrincipalPatentes() == null)
				if (tendencia.getIndicadorPatentes())
					tendencia.setFiltroPrincipalPatentes(panelPadre.preguntarFiltroPrincipal(tendencia, "Patentes"));
			if (tendencia.getFiltroPrincipalLicitaciones() == null)
				if (tendencia.getIndicadorLicitaciones())
					tendencia.setFiltroPrincipalLicitaciones(panelPadre.preguntarFiltroPrincipal(tendencia, "Licitaciones"));
			if (tendencia.getFiltroPrincipalLicitaciones() == null)
				if (tendencia.getIndicadorDocs())
					tendencia.setFiltroPrincipalLicitaciones(panelPadre.preguntarFiltroPrincipal(tendencia, "Documentos"));

			this.panelPadre.mostrarGraficaTendencia(tendencia, periodo, (GregorianCalendar)fechaInicio, (GregorianCalendar)fechaFin, sPeriodo);
		}

		if (e.getSource() == btnLicitacionSectores)
			dstdLicitacionSector.mostrar();

		if (e.getSource() == btnLicitacionLocalizacion)
			dstdLicitacionLocalizacion.mostrar();

		if (e.getSource() == btnPatenteLocalizacion)
			dsldPatenteLocalizacion.mostrar();

		if (e.getSource() == btnPatenteSectores)
			dstdPatenteSector.mostrar();
		
		if (e.getSource() == btnDocumentoClasificacion)
			dstdDocumentoClasificacion.mostrar();

		this.panelPadre.framePrincipal.frame.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
	}

	private DefaultComboBoxModel<String> getLista(String consulta) {
		Session session = Delphos.getSession();
		Query query = session.createSQLQuery(consulta);
		List<String> lista = query.list();
		lista.add(0, null);
		DefaultComboBoxModel<String> model = new DefaultComboBoxModel(lista.toArray(new String[lista.size()]));
		return model;
	}

	public DefaultComboBoxModel<String> getListaTipoLicitacion() {
		return getLista("SELECT DISTINCT(nombre) FROM TipoLicitacion ORDER BY nombre ASC");
	}

	@Override
	public void onAceptar(DelphosSelectionDialog dtd) {
		System.out.println("Aceptar");

		if (dtd == dstdLicitacionSector) {
			licitacionSectores = dtd.getSeleccion();
			lblLicitacionSectores.setText(dtd.getTextoSeleccion());
		}

		if (dtd == dstdLicitacionLocalizacion) {
			licitacionLocalizacion = dtd.getSeleccion();
			lblLicitacionLocalizacion.setText(dtd.getTextoSeleccion());
		}

		if (dtd == dsldPatenteLocalizacion) {
			patenteLocalizacion = dtd.getSeleccion();
			lblPatenteLocalizacion.setText(dtd.getTextoSeleccion());
		}

		if (dtd == dstdPatenteSector) {
			patenteSectores = dtd.getSeleccion();
			lblPatenteSectores.setText(dtd.getTextoSeleccion());
		}
		
		if (dtd == dstdDocumentoClasificacion) {
			documentoClasificacion = dtd.getSeleccion();
			lblDocumentoClasificacion.setText(dtd.getTextoSeleccion());
		}

	}

	@Override
	public void onCancelar(DelphosSelectionDialog dtd) {

	}

	@Override
	public void onBorrar(DelphosSelectionDialog dtd) {

	}

	@Override
	public void onCrear(DelphosSelectionDialog dtd) {

	}

}
