-- Este script CREA LA BASE DE DATOS

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `Host`;
DROP TABLE IF EXISTS `Peso`;
DROP TABLE IF EXISTS `Fuente`;

CREATE TABLE IF NOT EXISTS `Host` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idCategoria` int(11) DEFAULT NULL,
  `idSector` int(11) DEFAULT NULL,
  `localizacion` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `URL_UNICA` (`url`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Peso` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `descriptor` varchar(255) DEFAULT NULL,
  `frecuencia` int(11) NOT NULL,
  `idFuente` int(11) NOT NULL,
  `multiplicador` double DEFAULT NULL,
  `peso` double NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Descriptor_Fuente_Unica` ( `idFuente` , `descriptor` )
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Fuente` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(500) NOT NULL,
  `fechaActualizacion` datetime DEFAULT NULL,
  `idPadre` int(11) DEFAULT NULL,
  `documento` longtext,
  `titulo` varchar(256) DEFAULT NULL,
  `descripcion` varchar(1024) DEFAULT NULL,
  `idioma` varchar(10) DEFAULT NULL,
  `error` text,
  `parseada` tinyint(1) NOT NULL DEFAULT '0',
  `idHost` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `URL_UNICA` (`url`(200))
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `vacias`;
CREATE TABLE IF NOT EXISTS `vacias` (
  `palabra` varchar(15) DEFAULT NULL,
  `lenguaje` varchar(2) NOT NULL DEFAULT '??',
  KEY `lenguaje` (`lenguaje`),
  FULLTEXT KEY `palabra` (`palabra`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `vacias` (`palabra`, `lenguaje`) VALUES
('a', 'en'),
('about', 'en'),
('above', 'en'),
('across ', 'en'),
('after', 'en'),
('again', 'en'),
('against ', 'en'),
('almost ', 'en'),
('along', 'en'),
('already ', 'en'),
('also ', 'en'),
('although', 'en'),
('always ', 'en'),
('all', 'en'),
('am ', 'en'),
('among', 'en'),
('an', 'en'),
('and', 'en'),
('another', 'en'),
('any ', 'en'),
('anybody ', 'en'),
('anyone ', 'en'),
('anything ', 'en'),
('anywhere ', 'en'),
('are', 'en'),
('area', 'en'),
('areas ', 'en'),
('aren''t ', 'en'),
('around', 'en'),
('as ', 'en'),
('ask ', 'en'),
('asked', 'en'),
('asking', 'en'),
('asks', 'en'),
('at', 'en'),
('away ', 'en'),
('b', 'en'),
('back', 'en'),
('backed', 'en'),
('backing', 'en'),
('backs ', 'en'),
('be', 'en'),
('became ', 'en'),
('because ', 'en'),
('become ', 'en'),
('becomes ', 'en'),
('been', 'en'),
('before', 'en'),
('began', 'en'),
('behind', 'en'),
('being', 'en'),
('beings', 'en'),
('below', 'en'),
('best', 'en'),
('better', 'en'),
('between', 'en'),
('big', 'en'),
('both', 'en'),
('but', 'en'),
('by ', 'en'),
('c', 'en'),
('came ', 'en'),
('can', 'en'),
('can''t ', 'en'),
('cannot', 'en'),
('case ', 'en'),
('cases ', 'en'),
('certain ', 'en'),
('certainly ', 'en'),
('clear ', 'en'),
('clearly ', 'en'),
('come ', 'en'),
('could', 'en'),
('couldn''t ', 'en'),
('d', 'en'),
('daren''t ', 'en'),
('did', 'en'),
('didn''t', 'en'),
('differ', 'en'),
('different ', 'en'),
('differently ', 'en'),
('do', 'en'),
('does', 'en'),
('doesn''t ', 'en'),
('doing', 'en'),
('don''t ', 'en'),
('done', 'en'),
('down', 'en'),
('downed', 'en'),
('downing', 'en'),
('downs', 'en'),
('during', 'en'),
('e', 'en'),
('each', 'en'),
('early ', 'en'),
('either ', 'en'),
('end', 'en'),
('ended', 'en'),
('ending', 'en'),
('ends', 'en'),
('enough', 'en'),
('even', 'en'),
('evenly ', 'en'),
('ever', 'en'),
('every ', 'en'),
('everybody ', 'en'),
('everyone ', 'en'),
('everything ', 'en'),
('everywhere ', 'en'),
('f', 'en'),
('face', 'en'),
('faces ', 'en'),
('fact', 'en'),
('facts ', 'en'),
('far', 'en'),
('felt', 'en'),
('few', 'en'),
('find', 'en'),
('finds', 'en'),
('first', 'en'),
('five', 'en'),
('for', 'en'),
('four', 'en'),
('from', 'en'),
('full', 'en'),
('fully ', 'en'),
('further', 'en'),
('furthered', 'en'),
('furthering', 'en'),
('furthers', 'en'),
('g', 'en'),
('gave', 'en'),
('general', 'en'),
('generally ', 'en'),
('get', 'en'),
('gets', 'en'),
('give', 'en'),
('given', 'en'),
('gives', 'en'),
('go', 'en'),
('goes', 'en'),
('going', 'en'),
('good', 'en'),
('goods', 'en'),
('got', 'en'),
('great', 'en'),
('greater ', 'en'),
('greatest ', 'en'),
('group', 'en'),
('grouped', 'en'),
('grouping', 'en'),
('groups', 'en'),
('h', 'en'),
('had', 'en'),
('hadn''t', 'en'),
('has', 'en'),
('hasn''t ', 'en'),
('have', 'en'),
('haven''t ', 'en'),
('having', 'en'),
('he', 'en'),
('he''d ', 'en'),
('he''ll', 'en'),
('he''s ', 'en'),
('her', 'en'),
('here', 'en'),
('here''s ', 'en'),
('hers', 'en'),
('herself', 'en'),
('high', 'en'),
('higher', 'en'),
('highest', 'en'),
('him', 'en'),
('himself', 'en'),
('his', 'en'),
('how', 'en'),
('how''s ', 'en'),
('however', 'en'),
('i', 'en'),
('i''d', 'en'),
('i''ll', 'en'),
('i''m ', 'en'),
('i''ve ', 'en'),
('if', 'en'),
('important', 'en'),
('in', 'en'),
('interest ', 'en'),
('interested ', 'en'),
('interesting ', 'en'),
('interests ', 'en'),
('into', 'en'),
('is', 'en'),
('isn''t', 'en'),
('it', 'en'),
('it''s ', 'en'),
('its', 'en'),
('itself', 'en'),
('j', 'en'),
('just', 'en'),
('k', 'en'),
('keep', 'en'),
('keeps ', 'en'),
('kind', 'en'),
('knew', 'en'),
('know', 'en'),
('known', 'en'),
('knows', 'en'),
('l', 'en'),
('large', 'en'),
('largely ', 'en'),
('last', 'en'),
('later ', 'en'),
('latest ', 'en'),
('least ', 'en'),
('less ', 'en'),
('let', 'en'),
('let''s ', 'en'),
('lets', 'en'),
('like', 'en'),
('likely ', 'en'),
('long', 'en'),
('longer', 'en'),
('longest', 'en'),
('m', 'en'),
('made', 'en'),
('make', 'en'),
('making', 'en'),
('man ', 'en'),
('many ', 'en'),
('may ', 'en'),
('me ', 'en'),
('member ', 'en'),
('members ', 'en'),
('men ', 'en'),
('might', 'en'),
('mightn''t ', 'en'),
('more ', 'en'),
('most ', 'en'),
('mostly ', 'en'),
('mr', 'en'),
('mrs', 'en'),
('much ', 'en'),
('must ', 'en'),
('mustn''t ', 'en'),
('my ', 'en'),
('myself ', 'en'),
('n', 'en'),
('necessary ', 'en'),
('need', 'en'),
('needed', 'en'),
('needing', 'en'),
('needn''t ', 'en'),
('needs ', 'en'),
('never', 'en'),
('new', 'en'),
('newer', 'en'),
('newest', 'en'),
('next', 'en'),
('no', 'en'),
('nobody ', 'en'),
('non', 'en'),
('noone', 'en'),
('nor', 'en'),
('not', 'en'),
('nothing', 'en'),
('now', 'en'),
('nowhere', 'en'),
('number', 'en'),
('numbers', 'en'),
('o', 'en'),
('of', 'en'),
('off', 'en'),
('often', 'en'),
('old', 'en'),
('older', 'en'),
('oldest', 'en'),
('on', 'en'),
('once', 'en'),
('one', 'en'),
('only ', 'en'),
('open', 'en'),
('opened', 'en'),
('opening', 'en'),
('opens', 'en'),
('or', 'en'),
('order', 'en'),
('ordered', 'en'),
('ordering', 'en'),
('orders', 'en'),
('other', 'en'),
('others', 'en'),
('ought', 'en'),
('oughtn''t', 'en'),
('our', 'en'),
('ours', 'en'),
('ourselves', 'en'),
('out', 'en'),
('over', 'en'),
('own', 'en'),
('p', 'en'),
('part', 'en'),
('parted', 'en'),
('parting', 'en'),
('parts', 'en'),
('per ', 'en'),
('perhaps', 'en'),
('place ', 'en'),
('places ', 'en'),
('point', 'en'),
('pointed', 'en'),
('pointing', 'en'),
('points', 'en'),
('possible', 'en'),
('present ', 'en'),
('presented ', 'en'),
('presenting', 'en'),
('presents ', 'en'),
('problem', 'en'),
('problems', 'en'),
('put', 'en'),
('puts', 'en'),
('q', 'en'),
('quite', 'en'),
('r', 'en'),
('rather', 'en'),
('really ', 'en'),
('reuter', 'en'),
('right', 'en'),
('room', 'en'),
('rooms', 'en'),
('s', 'en'),
('said ', 'en'),
('same ', 'en'),
('saw ', 'en'),
('say ', 'en'),
('says ', 'en'),
('second', 'en'),
('seconds', 'en'),
('see ', 'en'),
('seem ', 'en'),
('seemed ', 'en'),
('seeming ', 'en'),
('seems ', 'en'),
('seen ', 'en'),
('sees ', 'en'),
('several ', 'en'),
('shall', 'en'),
('shan''t ', 'en'),
('she ', 'en'),
('she''d ', 'en'),
('she''ll ', 'en'),
('she''s ', 'en'),
('should', 'en'),
('shouldn''t ', 'en'),
('show', 'en'),
('showed', 'en'),
('showing', 'en'),
('shows', 'en'),
('side', 'en'),
('sides ', 'en'),
('since ', 'en'),
('small ', 'en'),
('smaller ', 'en'),
('smallest ', 'en'),
('so', 'en'),
('some ', 'en'),
('somebody ', 'en'),
('someone', 'en'),
('something ', 'en'),
('somewhere ', 'en'),
('state ', 'en'),
('states ', 'en'),
('still', 'en'),
('such ', 'en'),
('sure ', 'en'),
('t', 'en'),
('take', 'en'),
('taken', 'en'),
('than', 'en'),
('that', 'en'),
('that''s ', 'en'),
('the', 'en'),
('their', 'en'),
('theirs', 'en'),
('them ', 'en'),
('themselves ', 'en'),
('then', 'en'),
('there', 'en'),
('there''s ', 'en'),
('therefore ', 'en'),
('these ', 'en'),
('they ', 'en'),
('they''d ', 'en'),
('they''ll ', 'en'),
('they''re ', 'en'),
('they''ve ', 'en'),
('thing', 'en'),
('things', 'en'),
('think', 'en'),
('thinks', 'en'),
('this', 'en'),
('those', 'en'),
('though', 'en'),
('thought', 'en'),
('thoughts', 'en'),
('three', 'en'),
('through', 'en'),
('thus', 'en'),
('to', 'en'),
('today ', 'en'),
('together ', 'en'),
('too', 'en'),
('took', 'en'),
('toward', 'en'),
('turn', 'en'),
('turned', 'en'),
('turning', 'en'),
('turns', 'en'),
('two', 'en'),
('u', 'en'),
('under', 'en'),
('until', 'en'),
('up', 'en'),
('upon', 'en'),
('us', 'en'),
('use', 'en'),
('used', 'en'),
('uses', 'en'),
('v', 'en'),
('very ', 'en'),
('w', 'en'),
('want', 'en'),
('wanted', 'en'),
('wanting', 'en'),
('wants', 'en'),
('was', 'en'),
('wasn''t ', 'en'),
('way ', 'en'),
('ways ', 'en'),
('we', 'en'),
('we''d ', 'en'),
('we''ll ', 'en'),
('we''re ', 'en'),
('we''ve ', 'en'),
('well', 'en'),
('wells', 'en'),
('went', 'en'),
('were', 'en'),
('weren''t ', 'en'),
('what', 'en'),
('what''s ', 'en'),
('when', 'en'),
('when''s ', 'en'),
('where', 'en'),
('where''s ', 'en'),
('whether', 'en'),
('which', 'en'),
('while', 'en'),
('who', 'en'),
('whole', 'en'),
('whom', 'en'),
('whos''s ', 'en'),
('whose', 'en'),
('why ', 'en'),
('why''s ', 'en'),
('will', 'en'),
('with', 'en'),
('within', 'en'),
('without', 'en'),
('won''t ', 'en'),
('work', 'en'),
('worked', 'en'),
('working', 'en'),
('works', 'en'),
('would', 'en'),
('wouldn''t ', 'en'),
('x', 'en'),
('y', 'en'),
('year ', 'en'),
('years ', 'en'),
('yet ', 'en'),
('you ', 'en'),
('you''d ', 'en'),
('you''ll ', 'en'),
('you''re ', 'en'),
('you''ve ', 'en'),
('young ', 'en'),
('younger ', 'en'),
('youngest ', 'en'),
('your ', 'en'),
('yours ', 'en'),
('yourself ', 'en'),
('yourselves ', 'en'),
('z', 'en'),
('a', 'es'),
('añadio ', 'es'),
('aun', 'es'),
('actualmente ', 'es'),
('adelante', 'es'),
('ademas ', 'es'),
('afirmo ', 'es'),
('agrego ', 'es'),
('ahi', 'es'),
('ahora', 'es'),
('al', 'es'),
('algun ', 'es'),
('algo ', 'es'),
('alguna ', 'es'),
('algunas ', 'es'),
('alguno ', 'es'),
('algunos ', 'es'),
('alrededor ', 'es'),
('ambos ', 'es'),
('ante', 'es'),
('anterior', 'es'),
('antes', 'es'),
('apenas ', 'es'),
('aproximadam', 'es'),
('ente', 'es'),
('aqui ', 'es'),
('asi', 'es'),
('aseguro', 'es'),
('aunque', 'es'),
('ayer', 'es'),
('bajo ', 'es'),
('bien ', 'es'),
('buen ', 'es'),
('buena ', 'es'),
('buenas ', 'es'),
('bueno ', 'es'),
('buenos ', 'es'),
('como ', 'es'),
('cada', 'es'),
('casi', 'es'),
('cerca', 'es'),
('cierto', 'es'),
('cinco ', 'es'),
('comento ', 'es'),
('como ', 'es'),
('con', 'es'),
('conocer ', 'es'),
('considero', 'es'),
('considera', 'es'),
('contra ', 'es'),
('cosas', 'es'),
('creo', 'es'),
('cual', 'es'),
('cuales', 'es'),
('cualquier', 'es'),
('cuando', 'es'),
('cuanto ', 'es'),
('cuatro', 'es'),
('cuenta', 'es'),
('da', 'es'),
('dado ', 'es'),
('dan', 'es'),
('dar', 'es'),
('de', 'es'),
('debe', 'es'),
('deben ', 'es'),
('debido ', 'es'),
('decir', 'es'),
('dejo ', 'es'),
('del ', 'es'),
('demas ', 'es'),
('dentro ', 'es'),
('desde ', 'es'),
('despues ', 'es'),
('dice', 'es'),
('dicen', 'es'),
('dicho ', 'es'),
('dieron ', 'es'),
('diferente ', 'es'),
('diferentes ', 'es'),
('dijeron ', 'es'),
('dijo ', 'es'),
('dio ', 'es'),
('donde ', 'es'),
('dos', 'es'),
('durante ', 'es'),
('e', 'es'),
('ejemplo ', 'es'),
('el', 'es'),
('ella', 'es'),
('ellas', 'es'),
('ello ', 'es'),
('ellos ', 'es'),
('embargo ', 'es'),
('en', 'es'),
('encuentra ', 'es'),
('entonces', 'es'),
('entre', 'es'),
('era', 'es'),
('eraís', 'es'),
('eramos ', 'es'),
('eran', 'es'),
('eras', 'es'),
('eres', 'es'),
('es', 'es'),
('esa', 'es'),
('esas', 'es'),
('ese', 'es'),
('eso', 'es'),
('esos', 'es'),
('esta', 'es'),
('estan', 'es'),
('está', 'es'),
('estaba', 'es'),
('estabamos ', 'es'),
('estaban ', 'es'),
('estabas', 'es'),
('estaís', 'es'),
('estamos ', 'es'),
('estando ', 'es'),
('estad', 'es'),
('estada', 'es'),
('estado ', 'es'),
('estados ', 'es'),
('estadas', 'es'),
('estar', 'es'),
('estara', 'es'),
('estarán', 'es'),
('estaras', 'es'),
('estaría', 'es'),
('estaríamos ', 'es'),
('estarían', 'es'),
('estarías', 'es'),
('estaré', 'es'),
('estaremos ', 'es'),
('estareís', 'es'),
('estas', 'es'),
('este', 'es'),
('estemos ', 'es'),
('estén', 'es'),
('estes', 'es'),
('esteís', 'es'),
('esto', 'es'),
('estos', 'es'),
('estoy', 'es'),
('estuve ', 'es'),
('estuviera', 'es'),
('estuviéramos ', 'es'),
('estuvieras ', 'es'),
('estuvieron', 'es'),
('estuviese', 'es'),
('estuviésemos ', 'es'),
('estuviesen ', 'es'),
('estuvimos ', 'es'),
('estuviste', 'es'),
('estuvo', 'es'),
('ex', 'es'),
('existe ', 'es'),
('existen ', 'es'),
('explico ', 'es'),
('expreso ', 'es'),
('fin', 'es'),
('fue', 'es'),
('fuera ', 'es'),
('fueras ', 'es'),
('fuéramos ', 'es'),
('fueran ', 'es'),
('fueron ', 'es'),
('fuese', 'es'),
('fuésemos ', 'es'),
('fuesen ', 'es'),
('fueses ', 'es'),
('fuí', 'es'),
('fuimos ', 'es'),
('fuiste ', 'es'),
('fuisteis ', 'es'),
('gran ', 'es'),
('ha', 'es'),
('habéis ', 'es'),
('haber ', 'es'),
('había ', 'es'),
('habíamos ', 'es'),
('habían ', 'es'),
('habías ', 'es'),
('habida ', 'es'),
('habidas ', 'es'),
('habido ', 'es'),
('habidas ', 'es'),
('habiendo ', 'es'),
('habrá ', 'es'),
('habrán ', 'es'),
('habrás ', 'es'),
('habré ', 'es'),
('habreís ', 'es'),
('habremos ', 'es'),
('habría ', 'es'),
('habríamos ', 'es'),
('habrían ', 'es'),
('habrías ', 'es'),
('hace', 'es'),
('hacen', 'es'),
('hacer', 'es'),
('hacerlo ', 'es'),
('hacia', 'es'),
('haciendo', 'es'),
('han', 'es'),
('hasta ', 'es'),
('hay ', 'es'),
('haya ', 'es'),
('hayaís ', 'es'),
('hayamos ', 'es'),
('hayan ', 'es'),
('hayas ', 'es'),
('he', 'es'),
('hecho', 'es'),
('hemos ', 'es'),
('hicieron', 'es'),
('hizo ', 'es'),
('hoy ', 'es'),
('hube ', 'es'),
('hubiera ', 'es'),
('hubieramos ', 'es'),
('hubieran ', 'es'),
('hubieras ', 'es'),
('hubieron ', 'es'),
('hubiese ', 'es'),
('hubieses ', 'es'),
('hubiésemos ', 'es'),
('hubiesen ', 'es'),
('hubimos ', 'es'),
('hubiste ', 'es'),
('hubo ', 'es'),
('igual ', 'es'),
('incluso ', 'es'),
('indico ', 'es'),
('informo ', 'es'),
('junto ', 'es'),
('la', 'es'),
('lado ', 'es'),
('las', 'es'),
('le', 'es'),
('les', 'es'),
('llego ', 'es'),
('lleva ', 'es'),
('llevar ', 'es'),
('lo ', 'es'),
('los ', 'es'),
('luego ', 'es'),
('lugar ', 'es'),
('mas ', 'es'),
('manera ', 'es'),
('manifesto ', 'es'),
('mayor ', 'es'),
('me', 'es'),
('mediante ', 'es'),
('mejor ', 'es'),
('menciono ', 'es'),
('menos ', 'es'),
('mi', 'es'),
('mía', 'es'),
('mías ', 'es'),
('mío ', 'es'),
('míos ', 'es'),
('mis ', 'es'),
('mientras', 'es'),
('misma ', 'es'),
('mismas ', 'es'),
('mismo ', 'es'),
('mismos ', 'es'),
('momento ', 'es'),
('mucha ', 'es'),
('muchas ', 'es'),
('mucho ', 'es'),
('muchos ', 'es'),
('muy ', 'es'),
('nada', 'es'),
('nadie ', 'es'),
('ni ', 'es'),
('ningun ', 'es'),
('ninguna ', 'es'),
('ningunas ', 'es'),
('ninguno ', 'es'),
('ningunos ', 'es'),
('no', 'es'),
('nos', 'es'),
('nosotras ', 'es'),
('nosotros ', 'es'),
('nuestra ', 'es'),
('nuestras ', 'es'),
('nuestro ', 'es'),
('nuestros ', 'es'),
('nueva ', 'es'),
('nuevas ', 'es'),
('nuevo ', 'es'),
('nuevos ', 'es'),
('nunca ', 'es'),
('o', 'es'),
('ocho ', 'es'),
('os', 'es'),
('otra ', 'es'),
('otras ', 'es'),
('otro ', 'es'),
('otros ', 'es'),
('para', 'es'),
('parece', 'es'),
('parte ', 'es'),
('partir ', 'es'),
('pasada ', 'es'),
('pasado ', 'es'),
('pero ', 'es'),
('pesar', 'es'),
('poca', 'es'),
('pocas ', 'es'),
('poco ', 'es'),
('pocos ', 'es'),
('podemos ', 'es'),
('podra ', 'es'),
('podran ', 'es'),
('podria ', 'es'),
('podrian ', 'es'),
('poner ', 'es'),
('por ', 'es'),
('porque ', 'es'),
('posible ', 'es'),
('proximo ', 'es'),
('proximos ', 'es'),
('primer ', 'es'),
('primera ', 'es'),
('primero ', 'es'),
('primeros ', 'es'),
('principalment', 'es'),
('e', 'es'),
('propia ', 'es'),
('propias ', 'es'),
('propio ', 'es'),
('propios ', 'es'),
('pudo ', 'es'),
('pueda ', 'es'),
('puede ', 'es'),
('pueden ', 'es'),
('pues ', 'es'),
('que', 'es'),
('qué', 'es'),
('quedo ', 'es'),
('queremos ', 'es'),
('quien ', 'es'),
('quien ', 'es'),
('quienes ', 'es'),
('quiere ', 'es'),
('realizo ', 'es'),
('realizado', 'es'),
('realizar', 'es'),
('respecto ', 'es'),
('si', 'es'),
('solo', 'es'),
('se', 'es'),
('señalo', 'es'),
('sea', 'es'),
('seaís', 'es'),
('seamos ', 'es'),
('sean', 'es'),
('seas', 'es'),
('segun ', 'es'),
('segunda ', 'es'),
('segundo ', 'es'),
('seis', 'es'),
('sentid ', 'es'),
('sentida ', 'es'),
('sentidas ', 'es'),
('sentido ', 'es'),
('sentidos ', 'es'),
('ser', 'es'),
('sera', 'es'),
('será', 'es'),
('serán', 'es'),
('serás', 'es'),
('seré', 'es'),
('sereís', 'es'),
('seremos ', 'es'),
('sería', 'es'),
('seríamos ', 'es'),
('serían', 'es'),
('serías', 'es'),
('si', 'es'),
('sido ', 'es'),
('siempre ', 'es'),
('siendo', 'es'),
('siente', 'es'),
('siete', 'es'),
('sigue ', 'es'),
('siguiente ', 'es'),
('sin', 'es'),
('sino ', 'es'),
('sintiendo ', 'es'),
('sobre', 'es'),
('sois', 'es'),
('sola', 'es'),
('solamente ', 'es'),
('solas', 'es'),
('solo', 'es'),
('solos', 'es'),
('somos ', 'es'),
('son', 'es'),
('soy', 'es'),
('su', 'es'),
('sus', 'es'),
('suya', 'es'),
('suyas', 'es'),
('suyo', 'es'),
('suyos', 'es'),
('tal', 'es'),
('tambien ', 'es'),
('tampoco ', 'es'),
('tan ', 'es'),
('tanto ', 'es'),
('te', 'es'),
('tendrá ', 'es'),
('tendrán ', 'es'),
('tendrás ', 'es'),
('tendré ', 'es'),
('tendreís ', 'es'),
('tendremos ', 'es'),
('tendía ', 'es'),
('tendríamos ', 'es'),
('tendrían ', 'es'),
('tendrías ', 'es'),
('tened ', 'es'),
('teneís ', 'es'),
('tenemos ', 'es'),
('tener ', 'es'),
('tenga ', 'es'),
('tengaís ', 'es'),
('tengamos ', 'es'),
('tengan ', 'es'),
('tengas ', 'es'),
('tengo ', 'es'),
('tenía ', 'es'),
('teniamos ', 'es'),
('tenian ', 'es'),
('tenías ', 'es'),
('tenida ', 'es'),
('tenidas ', 'es'),
('tenido ', 'es'),
('tenidos ', 'es'),
('teniendo ', 'es'),
('tercera', 'es'),
('ti', 'es'),
('tiene ', 'es'),
('tienen ', 'es'),
('tienes ', 'es'),
('toda ', 'es'),
('todas ', 'es'),
('todavia ', 'es'),
('todo ', 'es'),
('todos ', 'es'),
('total ', 'es'),
('tras', 'es'),
('trata', 'es'),
('traves', 'es'),
('tres', 'es'),
('tu ', 'es'),
('tú ', 'es'),
('tus ', 'es'),
('tuve ', 'es'),
('tuviera', 'es'),
('tuviéramos ', 'es'),
('tuvieran ', 'es'),
('tuvieras', 'es'),
('tuvieron ', 'es'),
('tuviese', 'es'),
('tuvieseis', 'es'),
('tuviesen ', 'es'),
('tuviésemos ', 'es'),
('tuvieses', 'es'),
('tuvimos ', 'es'),
('tuviste ', 'es'),
('tuvisteis', 'es'),
('tuvo ', 'es'),
('tuya ', 'es'),
('tuyas ', 'es'),
('tuyo ', 'es'),
('tuyos ', 'es'),
('ultima ', 'es'),
('ultimas ', 'es'),
('ultimo ', 'es'),
('ultimos ', 'es'),
('un', 'es'),
('una', 'es'),
('unas ', 'es'),
('uno ', 'es'),
('unos ', 'es'),
('usted ', 'es'),
('va', 'es'),
('vamos ', 'es'),
('van', 'es'),
('varias ', 'es'),
('varios ', 'es'),
('veces', 'es'),
('ver', 'es'),
('vez', 'es'),
('vosotros ', 'es'),
('vosotras ', 'es'),
('vuestra ', 'es'),
('vuestras ', 'es'),
('vuestro ', 'es'),
('vuestros ', 'es'),
('y', 'es'),
('ya', 'es'),
('yo ', 'es');
