-- Este script CREA LA BASE DE DATOS

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `Host`;
DROP TABLE IF EXISTS `Descriptor`;
DROP TABLE IF EXISTS `Fuente`;
DROP TABLE IF EXISTS `Sector`;
DROP TABLE IF EXISTS `Localizacion`;
DROP TABLE IF EXISTS `TipoOrganizacion`;

CREATE TABLE IF NOT EXISTS `Host` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idTipoOrganizacion` int(11) DEFAULT NULL,
  `idSector` int(11) DEFAULT NULL,
  `idLocalizacion` int(11) DEFAULT NULL,
  `url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `URL_UNICA` (`url`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Descriptor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `descriptor` varchar(255) NOT NULL,
  `frecuencia` int(11) NOT NULL,
  `idFuente` int(11) NOT NULL,
  `multiplicador` double DEFAULT NULL,
  `peso` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Descriptor_Fuente_Unica` ( `idFuente` , `descriptor` )
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Fuente` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(2000) NOT NULL,
  `fechaActualizacion` datetime DEFAULT NULL,
  `idPadre` int(11) DEFAULT NULL,
  `profundidad` int(11) NOT NULL DEFAULT '0',
  `documento` longtext DEFAULT NULL,
  `titulo` varchar(256) DEFAULT NULL,
  `descripcion` varchar(1024) DEFAULT NULL,
  `idioma` varchar(10) DEFAULT NULL,
  `error` text DEFAULT NULL,
  `parseada` tinyint(1) NOT NULL DEFAULT '0',
  `idHost` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Sector` (
  `id` int(11) NOT NULL,
  `idPadre` int(11) DEFAULT NULL,
  `nombre` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `descripcion` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `TipoOrganizacion` (
  `id` int(11) NOT NULL,
  `idPadre` int(11) DEFAULT NULL,
  `nombre` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `descripcion` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `Localizacion` (
  `id` int(11) NOT NULL,
  `idPadre` int(11) DEFAULT NULL,
  `nombre` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `descripcion` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


DROP TABLE IF EXISTS `vacias`;
CREATE TABLE IF NOT EXISTS `vacias` (
  `palabra` varchar(15) DEFAULT NULL,
  `lenguaje` varchar(2) NOT NULL DEFAULT '??',
  KEY `lenguaje` (`lenguaje`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `vacias` (`palabra`, `lenguaje`) VALUES
('a', 'en'),
('about', 'en'),
('above', 'en'),
('across ', 'en'),
('after', 'en'),
('again', 'en'),
('against ', 'en'),
('almost ', 'en'),
('along', 'en'),
('already ', 'en'),
('also ', 'en'),
('although', 'en'),
('always ', 'en'),
('all', 'en'),
('am ', 'en'),
('among', 'en'),
('an', 'en'),
('and', 'en'),
('another', 'en'),
('any ', 'en'),
('anybody ', 'en'),
('anyone ', 'en'),
('anything ', 'en'),
('anywhere ', 'en'),
('are', 'en'),
('area', 'en'),
('areas ', 'en'),
('aren''t ', 'en'),
('around', 'en'),
('as ', 'en'),
('ask ', 'en'),
('asked', 'en'),
('asking', 'en'),
('asks', 'en'),
('at', 'en'),
('away ', 'en'),
('b', 'en'),
('back', 'en'),
('backed', 'en'),
('backing', 'en'),
('backs ', 'en'),
('be', 'en'),
('became ', 'en'),
('because ', 'en'),
('become ', 'en'),
('becomes ', 'en'),
('been', 'en'),
('before', 'en'),
('began', 'en'),
('behind', 'en'),
('being', 'en'),
('beings', 'en'),
('below', 'en'),
('best', 'en'),
('better', 'en'),
('between', 'en'),
('big', 'en'),
('both', 'en'),
('but', 'en'),
('by ', 'en'),
('c', 'en'),
('came ', 'en'),
('can', 'en'),
('can''t ', 'en'),
('cannot', 'en'),
('case ', 'en'),
('cases ', 'en'),
('certain ', 'en'),
('certainly ', 'en'),
('clear ', 'en'),
('clearly ', 'en'),
('come ', 'en'),
('could', 'en'),
('couldn''t ', 'en'),
('d', 'en'),
('daren''t ', 'en'),
('did', 'en'),
('didn''t', 'en'),
('differ', 'en'),
('different ', 'en'),
('differently ', 'en'),
('do', 'en'),
('does', 'en'),
('doesn''t ', 'en'),
('doing', 'en'),
('don''t ', 'en'),
('done', 'en'),
('down', 'en'),
('downed', 'en'),
('downing', 'en'),
('downs', 'en'),
('during', 'en'),
('e', 'en'),
('each', 'en'),
('early ', 'en'),
('either ', 'en'),
('end', 'en'),
('ended', 'en'),
('ending', 'en'),
('ends', 'en'),
('enough', 'en'),
('even', 'en'),
('evenly ', 'en'),
('ever', 'en'),
('every ', 'en'),
('everybody ', 'en'),
('everyone ', 'en'),
('everything ', 'en'),
('everywhere ', 'en'),
('f', 'en'),
('face', 'en'),
('faces ', 'en'),
('fact', 'en'),
('facts ', 'en'),
('far', 'en'),
('felt', 'en'),
('few', 'en'),
('find', 'en'),
('finds', 'en'),
('first', 'en'),
('five', 'en'),
('for', 'en'),
('four', 'en'),
('from', 'en'),
('full', 'en'),
('fully ', 'en'),
('further', 'en'),
('furthered', 'en'),
('furthering', 'en'),
('furthers', 'en'),
('g', 'en'),
('gave', 'en'),
('general', 'en'),
('generally ', 'en'),
('get', 'en'),
('gets', 'en'),
('give', 'en'),
('given', 'en'),
('gives', 'en'),
('go', 'en'),
('goes', 'en'),
('going', 'en'),
('good', 'en'),
('goods', 'en'),
('got', 'en'),
('great', 'en'),
('greater ', 'en'),
('greatest ', 'en'),
('group', 'en'),
('grouped', 'en'),
('grouping', 'en'),
('groups', 'en'),
('h', 'en'),
('had', 'en'),
('hadn''t', 'en'),
('has', 'en'),
('hasn''t ', 'en'),
('have', 'en'),
('haven''t ', 'en'),
('having', 'en'),
('he', 'en'),
('he''d ', 'en'),
('he''ll', 'en'),
('he''s ', 'en'),
('her', 'en'),
('here', 'en'),
('here''s ', 'en'),
('hers', 'en'),
('herself', 'en'),
('high', 'en'),
('higher', 'en'),
('highest', 'en'),
('him', 'en'),
('himself', 'en'),
('his', 'en'),
('how', 'en'),
('how''s ', 'en'),
('however', 'en'),
('i', 'en'),
('i''d', 'en'),
('i''ll', 'en'),
('i''m ', 'en'),
('i''ve ', 'en'),
('if', 'en'),
('important', 'en'),
('in', 'en'),
('interest ', 'en'),
('interested ', 'en'),
('interesting ', 'en'),
('interests ', 'en'),
('into', 'en'),
('is', 'en'),
('isn''t', 'en'),
('it', 'en'),
('it''s ', 'en'),
('its', 'en'),
('itself', 'en'),
('j', 'en'),
('just', 'en'),
('k', 'en'),
('keep', 'en'),
('keeps ', 'en'),
('kind', 'en'),
('knew', 'en'),
('know', 'en'),
('known', 'en'),
('knows', 'en'),
('l', 'en'),
('large', 'en'),
('largely ', 'en'),
('last', 'en'),
('later ', 'en'),
('latest ', 'en'),
('least ', 'en'),
('less ', 'en'),
('let', 'en'),
('let''s ', 'en'),
('lets', 'en'),
('like', 'en'),
('likely ', 'en'),
('long', 'en'),
('longer', 'en'),
('longest', 'en'),
('m', 'en'),
('made', 'en'),
('make', 'en'),
('making', 'en'),
('man ', 'en'),
('many ', 'en'),
('may ', 'en'),
('me ', 'en'),
('member ', 'en'),
('members ', 'en'),
('men ', 'en'),
('might', 'en'),
('mightn''t ', 'en'),
('more ', 'en'),
('most ', 'en'),
('mostly ', 'en'),
('mr', 'en'),
('mrs', 'en'),
('much ', 'en'),
('must ', 'en'),
('mustn''t ', 'en'),
('my ', 'en'),
('myself ', 'en'),
('n', 'en'),
('necessary ', 'en'),
('need', 'en'),
('needed', 'en'),
('needing', 'en'),
('needn''t ', 'en'),
('needs ', 'en'),
('never', 'en'),
('new', 'en'),
('newer', 'en'),
('newest', 'en'),
('next', 'en'),
('no', 'en'),
('nobody ', 'en'),
('non', 'en'),
('noone', 'en'),
('nor', 'en'),
('not', 'en'),
('nothing', 'en'),
('now', 'en'),
('nowhere', 'en'),
('number', 'en'),
('numbers', 'en'),
('o', 'en'),
('of', 'en'),
('off', 'en'),
('often', 'en'),
('old', 'en'),
('older', 'en'),
('oldest', 'en'),
('on', 'en'),
('once', 'en'),
('one', 'en'),
('only ', 'en'),
('open', 'en'),
('opened', 'en'),
('opening', 'en'),
('opens', 'en'),
('or', 'en'),
('order', 'en'),
('ordered', 'en'),
('ordering', 'en'),
('orders', 'en'),
('other', 'en'),
('others', 'en'),
('ought', 'en'),
('oughtn''t', 'en'),
('our', 'en'),
('ours', 'en'),
('ourselves', 'en'),
('out', 'en'),
('over', 'en'),
('own', 'en'),
('p', 'en'),
('part', 'en'),
('parted', 'en'),
('parting', 'en'),
('parts', 'en'),
('per ', 'en'),
('perhaps', 'en'),
('place ', 'en'),
('places ', 'en'),
('point', 'en'),
('pointed', 'en'),
('pointing', 'en'),
('points', 'en'),
('possible', 'en'),
('present ', 'en'),
('presented ', 'en'),
('presenting', 'en'),
('presents ', 'en'),
('problem', 'en'),
('problems', 'en'),
('put', 'en'),
('puts', 'en'),
('q', 'en'),
('quite', 'en'),
('r', 'en'),
('rather', 'en'),
('really ', 'en'),
('reuter', 'en'),
('right', 'en'),
('room', 'en'),
('rooms', 'en'),
('s', 'en'),
('said ', 'en'),
('same ', 'en'),
('saw ', 'en'),
('say ', 'en'),
('says ', 'en'),
('second', 'en'),
('seconds', 'en'),
('see ', 'en'),
('seem ', 'en'),
('seemed ', 'en'),
('seeming ', 'en'),
('seems ', 'en'),
('seen ', 'en'),
('sees ', 'en'),
('several ', 'en'),
('shall', 'en'),
('shan''t ', 'en'),
('she ', 'en'),
('she''d ', 'en'),
('she''ll ', 'en'),
('she''s ', 'en'),
('should', 'en'),
('shouldn''t ', 'en'),
('show', 'en'),
('showed', 'en'),
('showing', 'en'),
('shows', 'en'),
('side', 'en'),
('sides ', 'en'),
('since ', 'en'),
('small ', 'en'),
('smaller ', 'en'),
('smallest ', 'en'),
('so', 'en'),
('some ', 'en'),
('somebody ', 'en'),
('someone', 'en'),
('something ', 'en'),
('somewhere ', 'en'),
('state ', 'en'),
('states ', 'en'),
('still', 'en'),
('such ', 'en'),
('sure ', 'en'),
('t', 'en'),
('take', 'en'),
('taken', 'en'),
('than', 'en'),
('that', 'en'),
('that''s ', 'en'),
('the', 'en'),
('their', 'en'),
('theirs', 'en'),
('them ', 'en'),
('themselves ', 'en'),
('then', 'en'),
('there', 'en'),
('there''s ', 'en'),
('therefore ', 'en'),
('these ', 'en'),
('they ', 'en'),
('they''d ', 'en'),
('they''ll ', 'en'),
('they''re ', 'en'),
('they''ve ', 'en'),
('thing', 'en'),
('things', 'en'),
('think', 'en'),
('thinks', 'en'),
('this', 'en'),
('those', 'en'),
('though', 'en'),
('thought', 'en'),
('thoughts', 'en'),
('three', 'en'),
('through', 'en'),
('thus', 'en'),
('to', 'en'),
('today ', 'en'),
('together ', 'en'),
('too', 'en'),
('took', 'en'),
('toward', 'en'),
('turn', 'en'),
('turned', 'en'),
('turning', 'en'),
('turns', 'en'),
('two', 'en'),
('u', 'en'),
('under', 'en'),
('until', 'en'),
('up', 'en'),
('upon', 'en'),
('us', 'en'),
('use', 'en'),
('used', 'en'),
('uses', 'en'),
('v', 'en'),
('very ', 'en'),
('w', 'en'),
('want', 'en'),
('wanted', 'en'),
('wanting', 'en'),
('wants', 'en'),
('was', 'en'),
('wasn''t ', 'en'),
('way ', 'en'),
('ways ', 'en'),
('we', 'en'),
('we''d ', 'en'),
('we''ll ', 'en'),
('we''re ', 'en'),
('we''ve ', 'en'),
('well', 'en'),
('wells', 'en'),
('went', 'en'),
('were', 'en'),
('weren''t ', 'en'),
('what', 'en'),
('what''s ', 'en'),
('when', 'en'),
('when''s ', 'en'),
('where', 'en'),
('where''s ', 'en'),
('whether', 'en'),
('which', 'en'),
('while', 'en'),
('who', 'en'),
('whole', 'en'),
('whom', 'en'),
('whos''s ', 'en'),
('whose', 'en'),
('why ', 'en'),
('why''s ', 'en'),
('will', 'en'),
('with', 'en'),
('within', 'en'),
('without', 'en'),
('won''t ', 'en'),
('work', 'en'),
('worked', 'en'),
('working', 'en'),
('works', 'en'),
('would', 'en'),
('wouldn''t ', 'en'),
('x', 'en'),
('y', 'en'),
('year ', 'en'),
('years ', 'en'),
('yet ', 'en'),
('you ', 'en'),
('you''d ', 'en'),
('you''ll ', 'en'),
('you''re ', 'en'),
('you''ve ', 'en'),
('young ', 'en'),
('younger ', 'en'),
('youngest ', 'en'),
('your ', 'en'),
('yours ', 'en'),
('yourself ', 'en'),
('yourselves ', 'en'),
('z', 'en'),
('a', 'es'),
('añadio ', 'es'),
('aun', 'es'),
('actualmente ', 'es'),
('adelante', 'es'),
('ademas ', 'es'),
('afirmo ', 'es'),
('agrego ', 'es'),
('ahi', 'es'),
('ahora', 'es'),
('al', 'es'),
('algun ', 'es'),
('algo ', 'es'),
('alguna ', 'es'),
('algunas ', 'es'),
('alguno ', 'es'),
('algunos ', 'es'),
('alrededor ', 'es'),
('ambos ', 'es'),
('ante', 'es'),
('anterior', 'es'),
('antes', 'es'),
('apenas ', 'es'),
('aproximadam', 'es'),
('ente', 'es'),
('aqui ', 'es'),
('asi', 'es'),
('aseguro', 'es'),
('aunque', 'es'),
('ayer', 'es'),
('bajo ', 'es'),
('bien ', 'es'),
('buen ', 'es'),
('buena ', 'es'),
('buenas ', 'es'),
('bueno ', 'es'),
('buenos ', 'es'),
('como ', 'es'),
('cada', 'es'),
('casi', 'es'),
('cerca', 'es'),
('cierto', 'es'),
('cinco ', 'es'),
('comento ', 'es'),
('como ', 'es'),
('con', 'es'),
('conocer ', 'es'),
('considero', 'es'),
('considera', 'es'),
('contra ', 'es'),
('cosas', 'es'),
('creo', 'es'),
('cual', 'es'),
('cuales', 'es'),
('cualquier', 'es'),
('cuando', 'es'),
('cuanto ', 'es'),
('cuatro', 'es'),
('cuenta', 'es'),
('da', 'es'),
('dado ', 'es'),
('dan', 'es'),
('dar', 'es'),
('de', 'es'),
('debe', 'es'),
('deben ', 'es'),
('debido ', 'es'),
('decir', 'es'),
('dejo ', 'es'),
('del ', 'es'),
('demas ', 'es'),
('dentro ', 'es'),
('desde ', 'es'),
('despues ', 'es'),
('dice', 'es'),
('dicen', 'es'),
('dicho ', 'es'),
('dieron ', 'es'),
('diferente ', 'es'),
('diferentes ', 'es'),
('dijeron ', 'es'),
('dijo ', 'es'),
('dio ', 'es'),
('donde ', 'es'),
('dos', 'es'),
('durante ', 'es'),
('e', 'es'),
('ejemplo ', 'es'),
('el', 'es'),
('ella', 'es'),
('ellas', 'es'),
('ello ', 'es'),
('ellos ', 'es'),
('embargo ', 'es'),
('en', 'es'),
('encuentra ', 'es'),
('entonces', 'es'),
('entre', 'es'),
('era', 'es'),
('eraís', 'es'),
('eramos ', 'es'),
('eran', 'es'),
('eras', 'es'),
('eres', 'es'),
('es', 'es'),
('esa', 'es'),
('esas', 'es'),
('ese', 'es'),
('eso', 'es'),
('esos', 'es'),
('esta', 'es'),
('estan', 'es'),
('está', 'es'),
('estaba', 'es'),
('estabamos ', 'es'),
('estaban ', 'es'),
('estabas', 'es'),
('estaís', 'es'),
('estamos ', 'es'),
('estando ', 'es'),
('estad', 'es'),
('estada', 'es'),
('estado ', 'es'),
('estados ', 'es'),
('estadas', 'es'),
('estar', 'es'),
('estara', 'es'),
('estarán', 'es'),
('estaras', 'es'),
('estaría', 'es'),
('estaríamos ', 'es'),
('estarían', 'es'),
('estarías', 'es'),
('estaré', 'es'),
('estaremos ', 'es'),
('estareís', 'es'),
('estas', 'es'),
('este', 'es'),
('estemos ', 'es'),
('estén', 'es'),
('estes', 'es'),
('esteís', 'es'),
('esto', 'es'),
('estos', 'es'),
('estoy', 'es'),
('estuve ', 'es'),
('estuviera', 'es'),
('estuviéramos ', 'es'),
('estuvieras ', 'es'),
('estuvieron', 'es'),
('estuviese', 'es'),
('estuviésemos ', 'es'),
('estuviesen ', 'es'),
('estuvimos ', 'es'),
('estuviste', 'es'),
('estuvo', 'es'),
('ex', 'es'),
('existe ', 'es'),
('existen ', 'es'),
('explico ', 'es'),
('expreso ', 'es'),
('fin', 'es'),
('fue', 'es'),
('fuera ', 'es'),
('fueras ', 'es'),
('fuéramos ', 'es'),
('fueran ', 'es'),
('fueron ', 'es'),
('fuese', 'es'),
('fuésemos ', 'es'),
('fuesen ', 'es'),
('fueses ', 'es'),
('fuí', 'es'),
('fuimos ', 'es'),
('fuiste ', 'es'),
('fuisteis ', 'es'),
('gran ', 'es'),
('ha', 'es'),
('habéis ', 'es'),
('haber ', 'es'),
('había ', 'es'),
('habíamos ', 'es'),
('habían ', 'es'),
('habías ', 'es'),
('habida ', 'es'),
('habidas ', 'es'),
('habido ', 'es'),
('habidas ', 'es'),
('habiendo ', 'es'),
('habrá ', 'es'),
('habrán ', 'es'),
('habrás ', 'es'),
('habré ', 'es'),
('habreís ', 'es'),
('habremos ', 'es'),
('habría ', 'es'),
('habríamos ', 'es'),
('habrían ', 'es'),
('habrías ', 'es'),
('hace', 'es'),
('hacen', 'es'),
('hacer', 'es'),
('hacerlo ', 'es'),
('hacia', 'es'),
('haciendo', 'es'),
('han', 'es'),
('hasta ', 'es'),
('hay ', 'es'),
('haya ', 'es'),
('hayaís ', 'es'),
('hayamos ', 'es'),
('hayan ', 'es'),
('hayas ', 'es'),
('he', 'es'),
('hecho', 'es'),
('hemos ', 'es'),
('hicieron', 'es'),
('hizo ', 'es'),
('hoy ', 'es'),
('hube ', 'es'),
('hubiera ', 'es'),
('hubieramos ', 'es'),
('hubieran ', 'es'),
('hubieras ', 'es'),
('hubieron ', 'es'),
('hubiese ', 'es'),
('hubieses ', 'es'),
('hubiésemos ', 'es'),
('hubiesen ', 'es'),
('hubimos ', 'es'),
('hubiste ', 'es'),
('hubo ', 'es'),
('igual ', 'es'),
('incluso ', 'es'),
('indico ', 'es'),
('informo ', 'es'),
('junto ', 'es'),
('la', 'es'),
('lado ', 'es'),
('las', 'es'),
('le', 'es'),
('les', 'es'),
('llego ', 'es'),
('lleva ', 'es'),
('llevar ', 'es'),
('lo ', 'es'),
('los ', 'es'),
('luego ', 'es'),
('lugar ', 'es'),
('mas ', 'es'),
('manera ', 'es'),
('manifesto ', 'es'),
('mayor ', 'es'),
('me', 'es'),
('mediante ', 'es'),
('mejor ', 'es'),
('menciono ', 'es'),
('menos ', 'es'),
('mi', 'es'),
('mía', 'es'),
('mías ', 'es'),
('mío ', 'es'),
('míos ', 'es'),
('mis ', 'es'),
('mientras', 'es'),
('misma ', 'es'),
('mismas ', 'es'),
('mismo ', 'es'),
('mismos ', 'es'),
('momento ', 'es'),
('mucha ', 'es'),
('muchas ', 'es'),
('mucho ', 'es'),
('muchos ', 'es'),
('muy ', 'es'),
('nada', 'es'),
('nadie ', 'es'),
('ni ', 'es'),
('ningun ', 'es'),
('ninguna ', 'es'),
('ningunas ', 'es'),
('ninguno ', 'es'),
('ningunos ', 'es'),
('no', 'es'),
('nos', 'es'),
('nosotras ', 'es'),
('nosotros ', 'es'),
('nuestra ', 'es'),
('nuestras ', 'es'),
('nuestro ', 'es'),
('nuestros ', 'es'),
('nueva ', 'es'),
('nuevas ', 'es'),
('nuevo ', 'es'),
('nuevos ', 'es'),
('nunca ', 'es'),
('o', 'es'),
('ocho ', 'es'),
('os', 'es'),
('otra ', 'es'),
('otras ', 'es'),
('otro ', 'es'),
('otros ', 'es'),
('para', 'es'),
('parece', 'es'),
('parte ', 'es'),
('partir ', 'es'),
('pasada ', 'es'),
('pasado ', 'es'),
('pero ', 'es'),
('pesar', 'es'),
('poca', 'es'),
('pocas ', 'es'),
('poco ', 'es'),
('pocos ', 'es'),
('podemos ', 'es'),
('podra ', 'es'),
('podran ', 'es'),
('podria ', 'es'),
('podrian ', 'es'),
('poner ', 'es'),
('por ', 'es'),
('porque ', 'es'),
('posible ', 'es'),
('proximo ', 'es'),
('proximos ', 'es'),
('primer ', 'es'),
('primera ', 'es'),
('primero ', 'es'),
('primeros ', 'es'),
('principalment', 'es'),
('e', 'es'),
('propia ', 'es'),
('propias ', 'es'),
('propio ', 'es'),
('propios ', 'es'),
('pudo ', 'es'),
('pueda ', 'es'),
('puede ', 'es'),
('pueden ', 'es'),
('pues ', 'es'),
('que', 'es'),
('qué', 'es'),
('quedo ', 'es'),
('queremos ', 'es'),
('quien ', 'es'),
('quien ', 'es'),
('quienes ', 'es'),
('quiere ', 'es'),
('realizo ', 'es'),
('realizado', 'es'),
('realizar', 'es'),
('respecto ', 'es'),
('si', 'es'),
('solo', 'es'),
('se', 'es'),
('señalo', 'es'),
('sea', 'es'),
('seaís', 'es'),
('seamos ', 'es'),
('sean', 'es'),
('seas', 'es'),
('segun ', 'es'),
('segunda ', 'es'),
('segundo ', 'es'),
('seis', 'es'),
('sentid ', 'es'),
('sentida ', 'es'),
('sentidas ', 'es'),
('sentido ', 'es'),
('sentidos ', 'es'),
('ser', 'es'),
('sera', 'es'),
('será', 'es'),
('serán', 'es'),
('serás', 'es'),
('seré', 'es'),
('sereís', 'es'),
('seremos ', 'es'),
('sería', 'es'),
('seríamos ', 'es'),
('serían', 'es'),
('serías', 'es'),
('si', 'es'),
('sido ', 'es'),
('siempre ', 'es'),
('siendo', 'es'),
('siente', 'es'),
('siete', 'es'),
('sigue ', 'es'),
('siguiente ', 'es'),
('sin', 'es'),
('sino ', 'es'),
('sintiendo ', 'es'),
('sobre', 'es'),
('sois', 'es'),
('sola', 'es'),
('solamente ', 'es'),
('solas', 'es'),
('solo', 'es'),
('solos', 'es'),
('somos ', 'es'),
('son', 'es'),
('soy', 'es'),
('su', 'es'),
('sus', 'es'),
('suya', 'es'),
('suyas', 'es'),
('suyo', 'es'),
('suyos', 'es'),
('tal', 'es'),
('tambien ', 'es'),
('tampoco ', 'es'),
('tan ', 'es'),
('tanto ', 'es'),
('te', 'es'),
('tendrá ', 'es'),
('tendrán ', 'es'),
('tendrás ', 'es'),
('tendré ', 'es'),
('tendreís ', 'es'),
('tendremos ', 'es'),
('tendía ', 'es'),
('tendríamos ', 'es'),
('tendrían ', 'es'),
('tendrías ', 'es'),
('tened ', 'es'),
('teneís ', 'es'),
('tenemos ', 'es'),
('tener ', 'es'),
('tenga ', 'es'),
('tengaís ', 'es'),
('tengamos ', 'es'),
('tengan ', 'es'),
('tengas ', 'es'),
('tengo ', 'es'),
('tenía ', 'es'),
('teniamos ', 'es'),
('tenian ', 'es'),
('tenías ', 'es'),
('tenida ', 'es'),
('tenidas ', 'es'),
('tenido ', 'es'),
('tenidos ', 'es'),
('teniendo ', 'es'),
('tercera', 'es'),
('ti', 'es'),
('tiene ', 'es'),
('tienen ', 'es'),
('tienes ', 'es'),
('toda ', 'es'),
('todas ', 'es'),
('todavia ', 'es'),
('todo ', 'es'),
('todos ', 'es'),
('total ', 'es'),
('tras', 'es'),
('trata', 'es'),
('traves', 'es'),
('tres', 'es'),
('tu ', 'es'),
('tú ', 'es'),
('tus ', 'es'),
('tuve ', 'es'),
('tuviera', 'es'),
('tuviéramos ', 'es'),
('tuvieran ', 'es'),
('tuvieras', 'es'),
('tuvieron ', 'es'),
('tuviese', 'es'),
('tuvieseis', 'es'),
('tuviesen ', 'es'),
('tuviésemos ', 'es'),
('tuvieses', 'es'),
('tuvimos ', 'es'),
('tuviste ', 'es'),
('tuvisteis', 'es'),
('tuvo ', 'es'),
('tuya ', 'es'),
('tuyas ', 'es'),
('tuyo ', 'es'),
('tuyos ', 'es'),
('ultima ', 'es'),
('ultimas ', 'es'),
('ultimo ', 'es'),
('ultimos ', 'es'),
('un', 'es'),
('una', 'es'),
('unas ', 'es'),
('uno ', 'es'),
('unos ', 'es'),
('usted ', 'es'),
('va', 'es'),
('vamos ', 'es'),
('van', 'es'),
('varias ', 'es'),
('varios ', 'es'),
('veces', 'es'),
('ver', 'es'),
('vez', 'es'),
('vosotros ', 'es'),
('vosotras ', 'es'),
('vuestra ', 'es'),
('vuestras ', 'es'),
('vuestro ', 'es'),
('vuestros ', 'es'),
('y', 'es'),
('ya', 'es'),
('yo ', 'es'),
('au','fr'),
('aux','fr'),
('avec','fr'),
('ce','fr'),
('ces','fr'),
('dans','fr'),
('de','fr'),
('des','fr'),
('du','fr'),
('elle','fr'),
('en','fr'),
('et','fr'),
('eux','fr'),
('il','fr'),
('je','fr'),
('la','fr'),
('le','fr'),
('leur','fr'),
('lui','fr'),
('ma','fr'),
('mais','fr'),
('me','fr'),
('même','fr'),
('mes','fr'),
('moi','fr'),
('mon','fr'),
('ne','fr'),
('nos','fr'),
('notre','fr'),
('nous','fr'),
('on','fr'),
('ou','fr'),
('par','fr'),
('pas','fr'),
('pour','fr'),
('qu','fr'),
('que','fr'),
('qui','fr'),
('sa','fr'),
('se','fr'),
('ses','fr'),
('son','fr'),
('sur','fr'),
('ta','fr'),
('te','fr'),
('tes','fr'),
('toi','fr'),
('ton','fr'),
('tu','fr'),
('un','fr'),
('une','fr'),
('vos','fr'),
('votre','fr'),
('vous','fr'),
('c','fr'),
('d','fr'),
('j','fr'),
('l','fr'),
('à','fr'),
('m','fr'),
('n','fr'),
('s','fr'),
('t','fr'),
('y','fr'),
('été','fr'),
('étée','fr'),
('étées','fr'),
('étés','fr'),
('étant','fr'),
('suis','fr'),
('es','fr'),
('est','fr'),
('sommes','fr'),
('êtes','fr'),
('sont','fr'),
('serai','fr'),
('seras','fr'),
('sera','fr'),
('serons','fr'),
('serez','fr'),
('seront','fr'),
('serais','fr'),
('serait','fr'),
('serions','fr'),
('seriez','fr'),
('seraient','fr'),
('étais','fr'),
('était','fr'),
('étions','fr'),
('étiez','fr'),
('étaient','fr'),
('fus','fr'),
('fut','fr'),
('fûmes','fr'),
('fûtes','fr'),
('furent','fr'),
('sois','fr'),
('soit','fr'),
('soyons','fr'),
('soyez','fr'),
('soient','fr'),
('fusse','fr'),
('fusses','fr'),
('fût','fr'),
('fussions','fr'),
('fussiez','fr'),
('fussent','fr'),
('ayant','fr'),
('eu','fr'),
('eue','fr'),
('eues','fr'),
('eus','fr'),
('ai','fr'),
('as','fr'),
('avons','fr'),
('avez','fr'),
('ont','fr'),
('aurai','fr'),
('auras','fr'),
('aura','fr'),
('aurons','fr'),
('aurez','fr'),
('auront','fr'),
('aurais','fr'),
('aurait','fr'),
('aurions','fr'),
('auriez','fr'),
('auraient','fr'),
('avais','fr'),
('avait','fr'),
('avions','fr'),
('aviez','fr'),
('avaient','fr'),
('eut','fr'),
('eûmes','fr'),
('eûtes','fr'),
('eurent','fr'),
('aie','fr'),
('aies','fr'),
('ait','fr'),
('ayons','fr'),
('ayez','fr'),
('aient','fr'),
('eusse','fr'),
('eusses','fr'),
('eût','fr'),
('eussions','fr'),
('eussiez','fr'),
('eussent','fr'),
('ceci','fr'),
('cela','fr'),
('celà','fr'),
('cet','fr'),
('cette','fr'),
('ici','fr'),
('ils','fr'),
('les','fr'),
('leurs','fr'),
('quel','fr'),
('quels','fr'),
('quelle','fr'),
('quelles','fr'),
('sans','fr'),
('soi','fr'),
('de','pt'),
('a','pt'),
('o','pt'),
('que','pt'),
('e','pt'),
('do','pt'),
('da','pt'),
('em','pt'),
('um','pt'),
('para','pt'),
('com','pt'),
('não','pt'),
('uma','pt'),
('os','pt'),
('no','pt'),
('se','pt'),
('na','pt'),
('por','pt'),
('mais','pt'),
('as','pt'),
('dos','pt'),
('como','pt'),
('mas','pt'),
('ao','pt'),
('ele','pt'),
('das','pt'),
('à','pt'),
('seu','pt'),
('sua','pt'),
('ou','pt'),
('quando','pt'),
('muito','pt'),
('nos','pt'),
('já','pt'),
('eu','pt'),
('também','pt'),
('só','pt'),
('pelo','pt'),
('pela','pt'),
('até','pt'),
('isso','pt'),
('ela','pt'),
('entre','pt'),
('depois','pt'),
('sem','pt'),
('mesmo','pt'),
('aos','pt'),
('seus','pt'),
('quem','pt'),
('nas','pt'),
('me','pt'),
('esse','pt'),
('eles','pt'),
('você','pt'),
('essa','pt'),
('num','pt'),
('nem','pt'),
('suas','pt'),
('meu','pt'),
('às','pt'),
('minha','pt'),
('numa','pt'),
('pelos','pt'),
('elas','pt'),
('qual','pt'),
('nós','pt'),
('lhe','pt'),
('deles','pt'),
('essas','pt'),
('esses','pt'),
('pelas','pt'),
('este','pt'),
('dele','pt'),
('tu','pt'),
('te','pt'),
('vocês','pt'),
('vos','pt'),
('lhes','pt'),
('meus','pt'),
('minhas','pt'),
('teu','pt'),
('tua','pt'),
('teus','pt'),
('tuas','pt'),
('nosso','pt'),
('nossa','pt'),
('nossos','pt'),
('nossas','pt'),
('dela','pt'),
('delas','pt'),
('esta','pt'),
('estes','pt'),
('estas','pt'),
('aquele','pt'),
('aquela','pt'),
('aqueles','pt'),
('aquelas','pt'),
('isto','pt'),
('aquilo','pt'),
('estou','pt'),
('está','pt'),
('estamos','pt'),
('estão','pt'),
('estive','pt'),
('esteve','pt'),
('estivemos','pt'),
('estiveram','pt'),
('estava','pt'),
('estávamos','pt'),
('estavam','pt'),
('estivera','pt'),
('estivéramos','pt'),
('esteja','pt'),
('estejamos','pt'),
('estejam','pt'),
('estivesse','pt'),
('estivéssemos','pt'),
('estivessem','pt'),
('estiver','pt'),
('estivermos','pt'),
('estiverem','pt'),
('hei','pt'),
('há','pt'),
('havemos','pt'),
('hão','pt'),
('houve','pt'),
('houvemos','pt'),
('houveram','pt'),
('houvera','pt'),
('houvéramos','pt'),
('haja','pt'),
('hajamos','pt'),
('hajam','pt'),
('houvesse','pt'),
('houvéssemos','pt'),
('houvessem','pt'),
('houver','pt'),
('houvermos','pt'),
('houverem','pt'),
('houverei','pt'),
('houverá','pt'),
('houveremos','pt'),
('houverão','pt'),
('houveria','pt'),
('houveríamos','pt'),
('houveriam','pt'),
('sou','pt'),
('somos','pt'),
('são','pt'),
('era','pt'),
('éramos','pt'),
('eram','pt'),
('fui','pt'),
('foi','pt'),
('fomos','pt'),
('foram','pt'),
('fora','pt'),
('fôramos','pt'),
('seja','pt'),
('sejamos','pt'),
('sejam','pt'),
('fosse','pt'),
('fôssemos','pt'),
('fossem','pt'),
('for','pt'),
('formos','pt'),
('forem','pt'),
('serei','pt'),
('será','pt'),
('seremos','pt'),
('serão','pt'),
('seria','pt'),
('seríamos','pt'),
('seriam','pt'),
('tenho','pt'),
('tem','pt'),
('temos','pt'),
('tém','pt'),
('tinha','pt'),
('tínhamos','pt'),
('tinham','pt'),
('tive','pt'),
('teve','pt'),
('tivemos','pt'),
('tiveram','pt'),
('tivera','pt'),
('tivéramos','pt'),
('tenha','pt'),
('tenhamos','pt'),
('tenham','pt'),
('tivesse','pt'),
('tivéssemos','pt'),
('tivessem','pt'),
('tiver','pt'),
('tivermos','pt'),
('tiverem','pt'),
('terei','pt'),
('terá','pt'),
('teremos','pt'),
('terão','pt'),
('teria','pt'),
('teríamos','pt'),
('teriam','pt'),
('ad','it'),
('al','it'),
('allo','it'),
('ai','it'),
('agli','it'),
('all','it'),
('agl','it'),
('alla','it'),
('alle','it'),
('con','it'),
('col','it'),
('coi','it'),
('da','it'),
('dal','it'),
('dallo','it'),
('dai','it'),
('dagli','it'),
('dall','it'),
('dagl','it'),
('dalla','it'),
('dalle','it'),
('di','it'),
('del','it'),
('dello','it'),
('dei','it'),
('degli','it'),
('dell','it'),
('degl','it'),
('della','it'),
('delle','it'),
('in','it'),
('nel','it'),
('nello','it'),
('nei','it'),
('negli','it'),
('nell','it'),
('negl','it'),
('nella','it'),
('nelle','it'),
('su','it'),
('sul','it'),
('sullo','it'),
('sui','it'),
('sugli','it'),
('sull','it'),
('sugl','it'),
('sulla','it'),
('sulle','it'),
('per','it'),
('tra','it'),
('contro','it'),
('io','it'),
('tu','it'),
('lui','it'),
('lei','it'),
('noi','it'),
('voi','it'),
('loro','it'),
('mio','it'),
('mia','it'),
('miei','it'),
('mie','it'),
('tuo','it'),
('tua','it'),
('tuoi','it'),
('tue','it'),
('suo','it'),
('sua','it'),
('suoi','it'),
('sue','it'),
('nostro','it'),
('nostra','it'),
('nostri','it'),
('nostre','it'),
('vostro','it'),
('vostra','it'),
('vostri','it'),
('vostre','it'),
('mi','it'),
('ti','it'),
('ci','it'),
('vi','it'),
('lo','it'),
('la','it'),
('li','it'),
('le','it'),
('gli','it'),
('ne','it'),
('il','it'),
('un','it'),
('uno','it'),
('una','it'),
('ma','it'),
('ed','it'),
('se','it'),
('perché','it'),
('anche','it'),
('come','it'),
('dov','it'),
('dove','it'),
('che','it'),
('chi','it'),
('cui','it'),
('non','it'),
('più','it'),
('quale','it'),
('quanto','it'),
('quanti','it'),
('quanta','it'),
('quante','it'),
('quello','it'),
('quelli','it'),
('quella','it'),
('quelle','it'),
('questo','it'),
('questi','it'),
('questa','it'),
('queste','it'),
('si','it'),
('tutto','it'),
('tutti','it'),
('a','it'),
('c','it'),
('e','it'),
('i','it'),
('l','it'),
('o','it'),
('ho','it'),
('hai','it'),
('ha','it'),
('abbiamo','it'),
('avete','it'),
('hanno','it'),
('abbia','it'),
('abbiate','it'),
('abbiano','it'),
('avrò','it'),
('avrai','it'),
('avrà','it'),
('avremo','it'),
('avrete','it'),
('avranno','it'),
('avrei','it'),
('avresti','it'),
('avrebbe','it'),
('avremmo','it'),
('avreste','it'),
('avrebbero','it'),
('avevo','it'),
('avevi','it'),
('aveva','it'),
('avevamo','it'),
('avevate','it'),
('avevano','it'),
('ebbi','it'),
('avesti','it'),
('ebbe','it'),
('avemmo','it'),
('aveste','it'),
('ebbero','it'),
('avessi','it'),
('avesse','it'),
('avessimo','it'),
('avessero','it'),
('avendo','it'),
('avuto','it'),
('avuta','it'),
('avuti','it'),
('avute','it'),
('sono','it'),
('sei','it'),
('è','it'),
('siamo','it'),
('siete','it'),
('sia','it'),
('siate','it'),
('siano','it'),
('sarò','it'),
('sarai','it'),
('sarà','it'),
('saremo','it'),
('sarete','it'),
('saranno','it'),
('sarei','it'),
('saresti','it'),
('sarebbe','it'),
('saremmo','it'),
('sareste','it'),
('sarebbero','it'),
('ero','it'),
('eri','it'),
('era','it'),
('eravamo','it'),
('eravate','it'),
('erano','it'),
('fui','it'),
('fosti','it'),
('fu','it'),
('fummo','it'),
('foste','it'),
('furono','it'),
('fossi','it'),
('fosse','it'),
('fossimo','it'),
('fossero','it'),
('essendo','it'),
('faccio','it'),
('fai','it'),
('facciamo','it'),
('fanno','it'),
('faccia','it'),
('facciate','it'),
('facciano','it'),
('farò','it'),
('farai','it'),
('farà','it'),
('faremo','it'),
('farete','it'),
('faranno','it'),
('farei','it'),
('faresti','it'),
('farebbe','it'),
('faremmo','it'),
('fareste','it'),
('farebbero','it'),
('facevo','it'),
('facevi','it'),
('faceva','it'),
('facevamo','it'),
('facevate','it'),
('facevano','it'),
('feci','it'),
('facesti','it'),
('fece','it'),
('facemmo','it'),
('faceste','it'),
('fecero','it'),
('facessi','it'),
('facesse','it'),
('facessimo','it'),
('facessero','it'),
('facendo','it'),
('sto','it'),
('stai','it'),
('sta','it'),
('stiamo','it'),
('stanno','it'),
('stia','it'),
('stiate','it'),
('stiano','it'),
('starò','it'),
('starai','it'),
('starà','it'),
('staremo','it'),
('starete','it'),
('staranno','it'),
('starei','it'),
('staresti','it'),
('starebbe','it'),
('staremmo','it'),
('stareste','it'),
('starebbero','it'),
('stavo','it'),
('stavi','it'),
('stava','it'),
('stavamo','it'),
('stavate','it'),
('stavano','it'),
('stetti','it'),
('stesti','it'),
('stette','it'),
('stemmo','it'),
('steste','it'),
('stettero','it'),
('stessi','it'),
('stesse','it'),
('stessimo','it'),
('stessero','it'),
('stando','it'),
('aber','de'),
('alle','de'),
('allem','de'),
('allen','de'),
('aller','de'),
('alles','de'),
('als','de'),
('also','de'),
('am','de'),
('an','de'),
('ander','de'),
('andere','de'),
('anderem','de'),
('anderen','de'),
('anderer','de'),
('anderes','de'),
('anderm','de'),
('andern','de'),
('anderr','de'),
('anders','de'),
('auch','de'),
('auf','de'),
('aus','de'),
('bei','de'),
('bin','de'),
('bis','de'),
('bist','de'),
('da','de'),
('damit','de'),
('dann','de'),
('der','de'),
('den','de'),
('des','de'),
('dem','de'),
('die','de'),
('das','de'),
('daß','de'),
('derselbe','de'),
('derselben','de'),
('denselben','de'),
('desselben','de'),
('demselben','de'),
('dieselbe','de'),
('dieselben','de'),
('dasselbe','de'),
('dazu','de'),
('dein','de'),
('deine','de'),
('deinem','de'),
('deinen','de'),
('deiner','de'),
('deines','de'),
('denn','de'),
('derer','de'),
('dessen','de'),
('dich','de'),
('dir','de'),
('du','de'),
('dies','de'),
('diese','de'),
('diesem','de'),
('diesen','de'),
('dieser','de'),
('dieses','de'),
('doch','de'),
('dort','de'),
('durch','de'),
('ein','de'),
('eine','de'),
('einem','de'),
('einen','de'),
('einer','de'),
('eines','de'),
('einig','de'),
('einige','de'),
('einigem','de'),
('einigen','de'),
('einiger','de'),
('einiges','de'),
('einmal','de'),
('er','de'),
('ihn','de'),
('ihm','de'),
('es','de'),
('etwas','de'),
('euer','de'),
('eure','de'),
('eurem','de'),
('euren','de'),
('eurer','de'),
('eures','de'),
('für','de'),
('gegen','de'),
('gewesen','de'),
('hab','de'),
('habe','de'),
('haben','de'),
('hat','de'),
('hatte','de'),
('hatten','de'),
('hier','de'),
('hin','de'),
('hinter','de'),
('ich','de'),
('mich','de'),
('mir','de'),
('ihr','de'),
('ihre','de'),
('ihrem','de'),
('ihren','de'),
('ihrer','de'),
('ihres','de'),
('euch','de'),
('im','de'),
('in','de'),
('indem','de'),
('ins','de'),
('ist','de'),
('jede','de'),
('jedem','de'),
('jeden','de'),
('jeder','de'),
('jedes','de'),
('jene','de'),
('jenem','de'),
('jenen','de'),
('jener','de'),
('jenes','de'),
('jetzt','de'),
('kann','de'),
('kein','de'),
('keine','de'),
('keinem','de'),
('keinen','de'),
('keiner','de'),
('keines','de'),
('können','de'),
('könnte','de'),
('machen','de'),
('man','de'),
('manche','de'),
('manchem','de'),
('manchen','de'),
('mancher','de'),
('manches','de'),
('mein','de'),
('meine','de'),
('meinem','de'),
('meinen','de'),
('meiner','de'),
('meines','de'),
('mit','de'),
('muss','de'),
('musste','de'),
('nach','de'),
('nicht','de'),
('nichts','de'),
('noch','de'),
('nun','de'),
('nur','de'),
('ob','de'),
('oder','de'),
('ohne','de'),
('sehr','de'),
('sein','de'),
('seine','de'),
('seinem','de'),
('seinen','de'),
('seiner','de'),
('seines','de'),
('selbst','de'),
('sich','de'),
('sie','de'),
('ihnen','de'),
('sind','de'),
('so','de'),
('solche','de'),
('solchem','de'),
('solchen','de'),
('solcher','de'),
('solches','de'),
('soll','de'),
('sollte','de'),
('sondern','de'),
('sonst','de'),
('über','de'),
('um','de'),
('und','de'),
('uns','de'),
('unse','de'),
('unsem','de'),
('unsen','de'),
('unser','de'),
('unses','de'),
('unter','de'),
('viel','de'),
('vom','de'),
('von','de'),
('vor','de'),
('während','de'),
('war','de'),
('waren','de'),
('warst','de'),
('was','de'),
('weg','de'),
('weil','de'),
('weiter','de'),
('welche','de'),
('welchem','de'),
('welchen','de'),
('welcher','de'),
('welches','de'),
('wenn','de'),
('werde','de'),
('werden','de'),
('wie','de'),
('wieder','de'),
('will','de'),
('wir','de'),
('wird','de'),
('wirst','de'),
('wo','de'),
('wollen','de'),
('wollte','de'),
('würde','de'),
('würden','de'),
('zu','de'),
('zum','de'),
('zur','de'),
('zwar','de'),
('zwischen','de'),
('de','nl'),
('en','nl'),
('van','nl'),
('ik','nl'),
('te','nl'),
('dat','nl'),
('die','nl'),
('in','nl'),
('een','nl'),
('hij','nl'),
('het','nl'),
('niet','nl'),
('zijn','nl'),
('is','nl'),
('was','nl'),
('op','nl'),
('aan','nl'),
('met','nl'),
('als','nl'),
('voor','nl'),
('had','nl'),
('er','nl'),
('maar','nl'),
('om','nl'),
('hem','nl'),
('dan','nl'),
('zou','nl'),
('of','nl'),
('wat','nl'),
('mijn','nl'),
('men','nl'),
('dit','nl'),
('zo','nl'),
('door','nl'),
('over','nl'),
('ze','nl'),
('zich','nl'),
('bij','nl'),
('ook','nl'),
('tot','nl'),
('je','nl'),
('mij','nl'),
('uit','nl'),
('der','nl'),
('daar','nl'),
('haar','nl'),
('naar','nl'),
('heb','nl'),
('hoe','nl'),
('heeft','nl'),
('hebben','nl'),
('deze','nl'),
('u','nl'),
('want','nl'),
('nog','nl'),
('zal','nl'),
('me','nl'),
('zij','nl'),
('nu','nl'),
('ge','nl'),
('geen','nl'),
('omdat','nl'),
('iets','nl'),
('worden','nl'),
('toch','nl'),
('al','nl'),
('waren','nl'),
('veel','nl'),
('meer','nl'),
('doen','nl'),
('toen','nl'),
('moet','nl'),
('ben','nl'),
('zonder','nl'),
('kan','nl'),
('hun','nl'),
('dus','nl'),
('alles','nl'),
('onder','nl'),
('ja','nl'),
('eens','nl'),
('hier','nl'),
('wie','nl'),
('werd','nl'),
('altijd','nl'),
('doch','nl'),
('wordt','nl'),
('wezen','nl'),
('kunnen','nl'),
('ons','nl'),
('zelf','nl'),
('tegen','nl'),
('na','nl'),
('reeds','nl'),
('wil','nl'),
('kon','nl'),
('niets','nl'),
('uw','nl'),
('iemand','nl'),
('geweest','nl'),
('andere','nl'),
('och','sv'),
('det','sv'),
('att','sv'),
('i','sv'),
('en','sv'),
('jag','sv'),
('hon','sv'),
('som','sv'),
('han','sv'),
('på','sv'),
('den','sv'),
('med','sv'),
('var','sv'),
('sig','sv'),
('för','sv'),
('så','sv'),
('till','sv'),
('är','sv'),
('men','sv'),
('ett','sv'),
('om','sv'),
('hade','sv'),
('de','sv'),
('av','sv'),
('icke','sv'),
('mig','sv'),
('du','sv'),
('henne','sv'),
('då','sv'),
('sin','sv'),
('nu','sv'),
('har','sv'),
('inte','sv'),
('hans','sv'),
('honom','sv'),
('skulle','sv'),
('hennes','sv'),
('där','sv'),
('min','sv'),
('man','sv'),
('ej','sv'),
('vid','sv'),
('kunde','sv'),
('något','sv'),
('från','sv'),
('ut','sv'),
('när','sv'),
('efter','sv'),
('upp','sv'),
('vi','sv'),
('dem','sv'),
('vara','sv'),
('vad','sv'),
('över','sv'),
('än','sv'),
('dig','sv'),
('kan','sv'),
('sina','sv'),
('här','sv'),
('ha','sv'),
('mot','sv'),
('alla','sv'),
('under','sv'),
('någon','sv'),
('eller','sv'),
('allt','sv'),
('mycket','sv'),
('sedan','sv'),
('ju','sv'),
('denna','sv'),
('själv','sv'),
('detta','sv'),
('åt','sv'),
('utan','sv'),
('varit','sv'),
('hur','sv'),
('ingen','sv'),
('mitt','sv'),
('ni','sv'),
('bli','sv'),
('blev','sv'),
('oss','sv'),
('din','sv'),
('dessa','sv'),
('några','sv'),
('deras','sv'),
('blir','sv'),
('mina','sv'),
('samma','sv'),
('vilken','sv'),
('er','sv'),
('sådan','sv'),
('vår','sv'),
('blivit','sv'),
('dess','sv'),
('inom','sv'),
('mellan','sv'),
('sådant','sv'),
('varför','sv'),
('varje','sv'),
('vilka','sv'),
('ditt','sv'),
('vem','sv'),
('vilket','sv'),
('sitta','sv'),
('sådana','sv'),
('vart','sv'),
('dina','sv'),
('vars','sv'),
('vårt','sv'),
('våra','sv'),
('ert','sv'),
('era','sv'),
('vilkas','sv'),
('og','no'),
('i','no'),
('jeg','no'),
('det','no'),
('at','no'),
('en','no'),
('et','no'),
('den','no'),
('til','no'),
('er','no'),
('som','no'),
('på','no'),
('de','no'),
('med','no'),
('han','no'),
('av','no'),
('ikke','no'),
('ikkje','no'),
('der','no'),
('så','no'),
('var','no'),
('meg','no'),
('seg','no'),
('men','no'),
('ett','no'),
('har','no'),
('om','no'),
('vi','no'),
('min','no'),
('mitt','no'),
('ha','no'),
('hadde','no'),
('hun','no'),
('nå','no'),
('over','no'),
('da','no'),
('ved','no'),
('fra','no'),
('du','no'),
('ut','no'),
('sin','no'),
('dem','no'),
('oss','no'),
('opp','no'),
('man','no'),
('kan','no'),
('hans','no'),
('hvor','no'),
('eller','no'),
('hva','no'),
('skal','no'),
('selv','no'),
('sjøl','no'),
('her','no'),
('alle','no'),
('vil','no'),
('bli','no'),
('ble','no'),
('blei','no'),
('blitt','no'),
('kunne','no'),
('inn','no'),
('når','no'),
('være','no'),
('kom','no'),
('noen','no'),
('noe','no'),
('ville','no'),
('dere','no'),
('som','no'),
('deres','no'),
('kun','no'),
('ja','no'),
('etter','no'),
('ned','no'),
('skulle','no'),
('denne','no'),
('for','no'),
('deg','no'),
('si','no'),
('sine','no'),
('sitt','no'),
('mot','no'),
('å','no'),
('meget','no'),
('hvorfor','no'),
('dette','no'),
('disse','no'),
('uten','no'),
('hvordan','no'),
('ingen','no'),
('din','no'),
('ditt','no'),
('blir','no'),
('samme','no'),
('hvilken','no'),
('hvilke','no'),
('sånn','no'),
('inni','no'),
('mellom','no'),
('vår','no'),
('hver','no'),
('hvem','no'),
('vors','no'),
('hvis','no'),
('både','no'),
('bare','no'),
('enn','no'),
('fordi','no'),
('før','no'),
('mange','no'),
('også','no'),
('slik','no'),
('vært','no'),
('være','no'),
('båe','no'),
('begge','no'),
('siden','no'),
('dykk','no'),
('dykkar','no'),
('dei','no'),
('deira','no'),
('deires','no'),
('deim','no'),
('di','no'),
('då','no'),
('eg','no'),
('ein','no'),
('eit','no'),
('eitt','no'),
('elles','no'),
('honom','no'),
('hjå','no'),
('ho','no'),
('hoe','no'),
('henne','no'),
('hennar','no'),
('hennes','no'),
('hoss','no'),
('hossen','no'),
('ikkje','no'),
('ingi','no'),
('inkje','no'),
('korleis','no'),
('korso','no'),
('kva','no'),
('kvar','no'),
('kvarhelst','no'),
('kven','no'),
('kvi','no'),
('kvifor','no'),
('me','no'),
('medan','no'),
('mi','no'),
('mine','no'),
('mykje','no'),
('no','no'),
('nokon','no'),
('noka','no'),
('nokor','no'),
('noko','no'),
('nokre','no'),
('si','no'),
('sia','no'),
('sidan','no'),
('so','no'),
('somt','no'),
('somme','no'),
('um','no'),
('upp','no'),
('vere','no'),
('vore','no'),
('verte','no'),
('vort','no'),
('varte','no'),
('vart','no'),
('og','da'),
('i','da'),
('jeg','da'),
('det','da'),
('at','da'),
('en','da'),
('den','da'),
('til','da'),
('er','da'),
('som','da'),
('på','da'),
('de','da'),
('med','da'),
('han','da'),
('af','da'),
('for','da'),
('ikke','da'),
('der','da'),
('var','da'),
('mig','da'),
('sig','da'),
('men','da'),
('et','da'),
('har','da'),
('om','da'),
('vi','da'),
('min','da'),
('havde','da'),
('ham','da'),
('hun','da'),
('nu','da'),
('over','da'),
('da','da'),
('fra','da'),
('du','da'),
('ud','da'),
('sin','da'),
('dem','da'),
('os','da'),
('op','da'),
('man','da'),
('hans','da'),
('hvor','da'),
('eller','da'),
('hvad','da'),
('skal','da'),
('selv','da'),
('her','da'),
('alle','da'),
('vil','da'),
('blev','da'),
('kunne','da'),
('ind','da'),
('når','da'),
('være','da'),
('dog','da'),
('noget','da'),
('ville','da'),
('jo','da'),
('deres','da'),
('efter','da'),
('ned','da'),
('skulle','da'),
('denne','da'),
('end','da'),
('dette','da'),
('mit','da'),
('også','da'),
('under','da'),
('have','da'),
('dig','da'),
('anden','da'),
('hende','da'),
('mine','da'),
('alt','da'),
('meget','da'),
('sit','da'),
('sine','da'),
('vor','da'),
('mod','da'),
('disse','da'),
('hvis','da'),
('din','da'),
('nogle','da'),
('hos','da'),
('blive','da'),
('mange','da'),
('ad','da'),
('bliver','da'),
('hendes','da'),
('været','da'),
('thi','da'),
('jer','da'),
('sådan','da'),
('É','ru'),
('×','ru'),
('×Ï','ru'),
('ÎÅ','ru'),
('ÞÔÏ','ru'),
('ÏÎ','ru'),
('ÎÁ','ru'),
('Ñ','ru'),
('Ó','ru'),
('ÓÏ','ru'),
('ËÁË','ru'),
('Á','ru'),
('ÔÏ','ru'),
('×ÓÅ','ru'),
('ÏÎÁ','ru'),
('ÔÁË','ru'),
('ÅÇÏ','ru'),
('ÎÏ','ru'),
('ÄÁ','ru'),
('ÔÙ','ru'),
('Ë','ru'),
('Õ','ru'),
('ÖÅ','ru'),
('×Ù','ru'),
('ÚÁ','ru'),
('ÂÙ','ru'),
('ÐÏ','ru'),
('ÔÏÌØËÏ','ru'),
('ÅÅ','ru'),
('ÍÎÅ','ru'),
('ÂÙÌÏ','ru'),
('×ÏÔ','ru'),
('ÏÔ','ru'),
('ÍÅÎÑ','ru'),
('ÅÝÅ','ru'),
('ÎÅÔ','ru'),
('Ï','ru'),
('ÉÚ','ru'),
('ÅÍÕ','ru'),
('ÔÅÐÅÒØ','ru'),
('ËÏÇÄÁ','ru'),
('ÄÁÖÅ','ru'),
('ÎÕ','ru'),
('×ÄÒÕÇ','ru'),
('ÌÉ','ru'),
('ÅÓÌÉ','ru'),
('ÕÖÅ','ru'),
('ÉÌÉ','ru'),
('ÎÉ','ru'),
('ÂÙÔØ','ru'),
('ÂÙÌ','ru'),
('ÎÅÇÏ','ru'),
('ÄÏ','ru'),
('×ÁÓ','ru'),
('ÎÉÂÕÄØ','ru'),
('ÏÐÑÔØ','ru'),
('ÕÖ','ru'),
('×ÁÍ','ru'),
('ÓËÁÚÁÌ','ru'),
('×ÅÄØ','ru'),
('ÔÁÍ','ru'),
('ÐÏÔÏÍ','ru'),
('ÓÅÂÑ','ru'),
('ÎÉÞÅÇÏ','ru'),
('ÅÊ','ru'),
('ÍÏÖÅÔ','ru'),
('ÏÎÉ','ru'),
('ÔÕÔ','ru'),
('ÇÄÅ','ru'),
('ÅÓÔØ','ru'),
('ÎÁÄÏ','ru'),
('ÎÅÊ','ru'),
('ÄÌÑ','ru'),
('ÍÙ','ru'),
('ÔÅÂÑ','ru'),
('ÉÈ','ru'),
('ÞÅÍ','ru'),
('ÂÙÌÁ','ru'),
('ÓÁÍ','ru'),
('ÞÔÏÂ','ru'),
('ÂÅÚ','ru'),
('ÂÕÄÔÏ','ru'),
('ÞÅÌÏ×ÅË','ru'),
('ÞÅÇÏ','ru'),
('ÒÁÚ','ru'),
('ÔÏÖÅ','ru'),
('ÓÅÂÅ','ru'),
('ÐÏÄ','ru'),
('ÖÉÚÎØ','ru'),
('ÂÕÄÅÔ','ru'),
('Ö','ru'),
('ÔÏÇÄÁ','ru'),
('ËÔÏ','ru'),
('ÜÔÏÔ','ru'),
('ÇÏ×ÏÒÉÌ','ru'),
('ÔÏÇÏ','ru'),
('ÐÏÔÏÍÕ','ru'),
('ÜÔÏÇÏ','ru'),
('ËÁËÏÊ','ru'),
('ÓÏ×ÓÅÍ','ru'),
('ÎÉÍ','ru'),
('ÚÄÅÓØ','ru'),
('ÜÔÏÍ','ru'),
('ÏÄÉÎ','ru'),
('ÐÏÞÔÉ','ru'),
('ÍÏÊ','ru'),
('ÔÅÍ','ru'),
('ÞÔÏÂÙ','ru'),
('ÎÅÅ','ru'),
('ËÁÖÅÔÓÑ','ru'),
('ÓÅÊÞÁÓ','ru'),
('ÂÙÌÉ','ru'),
('ËÕÄÁ','ru'),
('ÚÁÞÅÍ','ru'),
('ÓËÁÚÁÔØ','ru'),
('×ÓÅÈ','ru'),
('ÎÉËÏÇÄÁ','ru'),
('ÓÅÇÏÄÎÑ','ru'),
('ÍÏÖÎÏ','ru'),
('ÐÒÉ','ru'),
('ÎÁËÏÎÅÃ','ru'),
('Ä×Á','ru'),
('ÏÂ','ru'),
('ÄÒÕÇÏÊ','ru'),
('ÈÏÔØ','ru'),
('ÐÏÓÌÅ','ru'),
('ÎÁÄ','ru'),
('ÂÏÌØÛÅ','ru'),
('ÔÏÔ','ru'),
('ÞÅÒÅÚ','ru'),
('ÜÔÉ','ru'),
('ÎÁÓ','ru'),
('ÐÒÏ','ru'),
('×ÓÅÇÏ','ru'),
('ÎÉÈ','ru'),
('ËÁËÁÑ','ru'),
('ÍÎÏÇÏ','ru'),
('ÒÁÚ×Å','ru'),
('ÓËÁÚÁÌÁ','ru'),
('ÔÒÉ','ru'),
('ÜÔÕ','ru'),
('ÍÏÑ','ru'),
('×ÐÒÏÞÅÍ','ru'),
('ÈÏÒÏÛÏ','ru'),
('Ó×ÏÀ','ru'),
('ÜÔÏÊ','ru'),
('ÐÅÒÅÄ','ru'),
('ÉÎÏÇÄÁ','ru'),
('ÌÕÞÛÅ','ru'),
('ÞÕÔØ','ru'),
('ÔÏÍ','ru'),
('ÎÅÌØÚÑ','ru'),
('ÔÁËÏÊ','ru'),
('ÉÍ','ru'),
('ÂÏÌÅÅ','ru'),
('×ÓÅÇÄÁ','ru'),
('ËÏÎÅÞÎÏ','ru'),
('×ÓÀ','ru'),
('ÍÅÖÄÕ','ru'),
('olla','fi'),
('olen','fi'),
('olet','fi'),
('on','fi'),
('olemme','fi'),
('olette','fi'),
('ovat','fi'),
('ole','fi'),
('oli','fi'),
('olisi','fi'),
('olisit','fi'),
('olisin','fi'),
('olisimme','fi'),
('olisitte','fi'),
('olisivat','fi'),
('olit','fi'),
('olin','fi'),
('olimme','fi'),
('olitte','fi'),
('olivat','fi'),
('ollut','fi'),
('olleet','fi'),
('en','fi'),
('et','fi'),
('ei','fi'),
('emme','fi'),
('ette','fi'),
('eivät','fi'),
('minä','fi'),
('sinä','fi'),
('hän','fi'),
('me','fi'),
('te','fi'),
('he','fi'),
('tämä','fi'),
('tuo','fi'),
('se','fi'),
('nämä','fi'),
('nuo','fi'),
('ne','fi'),
('kuka','fi'),
('ketkä','fi'),
('mikä','fi'),
('mitkä','fi'),
('joka','fi'),
('jotka','fi'),
('että','fi'),
('ja','fi'),
('jos','fi'),
('koska','fi'),
('kuin','fi'),
('mutta','fi'),
('niin','fi'),
('sekä','fi'),
('sillä','fi'),
('tai','fi'),
('vaan','fi'),
('vai','fi'),
('vaikka','fi'),
('kanssa','fi'),
('mukaan','fi'),
('noin','fi'),
('poikki','fi'),
('yli','fi'),
('kun','fi'),
('niin','fi'),
('nyt','fi'),
('itse','fi'),
("a",'ga'),
("ach",'ga'),
("ag",'ga'),
("agus",'ga'),
("an",'ga'),
("aon",'ga'),
("ar",'ga'),
("arna",'ga'),
("as",'ga'),
("b'",'ga'),
("ba",'ga'),
("beirt",'ga'),
("bhÃºr",'ga'),
("caoga",'ga'),
("ceathair",'ga'),
("ceathrar",'ga'),
("chomh",'ga'),
("chtÃ³",'ga'),
("chuig",'ga'),
("chun",'ga'),
("cois",'ga'),
("cÃ©ad",'ga'),
("cÃºig",'ga'),
("cÃºigear",'ga'),
("d'",'ga'),
("daichead",'ga'),
("dar",'ga'),
("de",'ga'),
("deich",'ga'),
("deichniÃºr",'ga'),
("den",'ga'),
("dhÃ¡",'ga'),
("do",'ga'),
("don",'ga'),
("dtÃ­",'ga'),
("dÃ¡",'ga'),
("dÃ¡r",'ga'),
("dÃ³",'ga'),
("faoi",'ga'),
("faoin",'ga'),
("faoina",'ga'),
("faoinÃ¡r",'ga'),
("fara",'ga'),
("fiche",'ga'),
("gach",'ga'),
("gan",'ga'),
("go",'ga'),
("gur",'ga'),
("haon",'ga'),
("hocht",'ga'),
("i",'ga'),
("iad",'ga'),
("idir",'ga'),
("in",'ga'),
("ina",'ga'),
("ins",'ga'),
("inÃ¡r",'ga'),
("is",'ga'),
("le",'ga'),
("leis",'ga'),
("lena",'ga'),
("lenÃ¡r",'ga'),
("m'",'ga'),
("mar",'ga'),
("mo",'ga'),
("mÃ©",'ga'),
("na",'ga'),
("nach",'ga'),
("naoi",'ga'),
("naonÃºr",'ga'),
("nÃ¡",'ga'),
("nÃ­",'ga'),
("nÃ­or",'ga'),
("nÃ³",'ga'),
("nÃ³cha",'ga'),
("ocht",'ga'),
("ochtar",'ga'),
("os",'ga'),
("roimh",'ga'),
("sa",'ga'),
("seacht",'ga'),
("seachtar",'ga'),
("seachtÃ³",'ga'),
("seasca",'ga'),
("seisear",'ga'),
("siad",'ga'),
("sibh",'ga'),
("sinn",'ga'),
("sna",'ga'),
("sÃ©",'ga'),
("sÃ­",'ga'),
("tar",'ga'),
("thar",'ga'),
("thÃº",'ga'),
("triÃºr",'ga'),
("trÃ­",'ga'),
("trÃ­na",'ga'),
("trÃ­nÃ¡r",'ga'),
("trÃ­ocha",'ga'),
("tÃº",'ga'),
("um",'ga'),
("Ã¡r",'ga'),
("Ã©",'ga'),
("Ã©is",'ga'),
("Ã­",'ga'),
("Ã³",'ga'),
("Ã³n",'ga'),
("Ã³na",'ga'),
("Ã³nÃ¡r",'ga'),
("a",'hu'),
("ahogy",'hu'),
("ahol",'hu'),
("aki",'hu'),
("akik",'hu'),
("akkor",'hu'),
("alatt",'hu'),
("által",'hu'),
("általában",'hu'),
("amely",'hu'),
("amelyek",'hu'),
("amelyekben",'hu'),
("amelyeket",'hu'),
("amelyet",'hu'),
("amelynek",'hu'),
("ami",'hu'),
("amit",'hu'),
("amolyan",'hu'),
("amíg",'hu'),
("amikor",'hu'),
("át",'hu'),
("abban",'hu'),
("ahhoz",'hu'),
("annak",'hu'),
("arra",'hu'),
("arról",'hu'),
("az",'hu'),
("azok",'hu'),
("azon",'hu'),
("azt",'hu'),
("azzal",'hu'),
("azért",'hu'),
("aztán",'hu'),
("azután",'hu'),
("azonban",'hu'),
("bár",'hu'),
("be",'hu'),
("belül",'hu'),
("benne",'hu'),
("cikk",'hu'),
("cikkek",'hu'),
("cikkeket",'hu'),
("csak",'hu'),
("de",'hu'),
("e",'hu'),
("eddig",'hu'),
("egész",'hu'),
("egy",'hu'),
("egyes",'hu'),
("egyetlen",'hu'),
("egyéb",'hu'),
("egyik",'hu'),
("egyre",'hu'),
("ekkor",'hu'),
("el",'hu'),
("elég",'hu'),
("ellen",'hu'),
("elõ",'hu'),
("elõször",'hu'),
("elõtt",'hu'),
("elsõ",'hu'),
("én",'hu'),
("éppen",'hu'),
("ebben",'hu'),
("ehhez",'hu'),
("emilyen",'hu'),
("ennek",'hu'),
("erre",'hu'),
("ez",'hu'),
("ezt",'hu'),
("ezek",'hu'),
("ezen",'hu'),
("ezzel",'hu'),
("ezért",'hu'),
("és",'hu'),
("fel",'hu'),
("felé",'hu'),
("hanem",'hu'),
("hiszen",'hu'),
("hogy",'hu'),
("hogyan",'hu'),
("igen",'hu'),
("így",'hu'),
("illetve",'hu'),
("ill.",'hu'),
("ill",'hu'),
("ilyen",'hu'),
("ilyenkor",'hu'),
("ison",'hu'),
("ismét",'hu'),
("itt",'hu'),
("jó",'hu'),
("jól",'hu'),
("jobban",'hu'),
("kell",'hu'),
("kellett",'hu'),
("keresztül",'hu'),
("keressünk",'hu'),
("ki",'hu'),
("kívül",'hu'),
("között",'hu'),
("közül",'hu'),
("legalább",'hu'),
("lehet",'hu'),
("lehetett",'hu'),
("legyen",'hu'),
("lenne",'hu'),
("lenni",'hu'),
("lesz",'hu'),
("lett",'hu'),
("maga",'hu'),
("magát",'hu'),
("majd",'hu'),
("majd",'hu'),
("már",'hu'),
("más",'hu'),
("másik",'hu'),
("meg",'hu'),
("még",'hu'),
("mellett",'hu'),
("mert",'hu'),
("mely",'hu'),
("melyek",'hu'),
("mi",'hu'),
("mit",'hu'),
("míg",'hu'),
("miért",'hu'),
("milyen",'hu'),
("mikor",'hu'),
("minden",'hu'),
("mindent",'hu'),
("mindenki",'hu'),
("mindig",'hu'),
("mint",'hu'),
("mintha",'hu'),
("mivel",'hu'),
("most",'hu'),
("nagy",'hu'),
("nagyobb",'hu'),
("nagyon",'hu'),
("ne",'hu'),
("néha",'hu'),
("nekem",'hu'),
("neki",'hu'),
("nem",'hu'),
("néhány",'hu'),
("nélkül",'hu'),
("nincs",'hu'),
("olyan",'hu'),
("ott",'hu'),
("össze",'hu'),
("õ",'hu'),
("õk",'hu'),
("õket",'hu'),
("pedig",'hu'),
("persze",'hu'),
("rá",'hu'),
("s",'hu'),
("saját",'hu'),
("sem",'hu'),
("semmi",'hu'),
("sok",'hu'),
("sokat",'hu'),
("sokkal",'hu'),
("számára",'hu'),
("szemben",'hu'),
("szerint",'hu'),
("szinte",'hu'),
("talán",'hu'),
("tehát",'hu'),
("teljes",'hu'),
("tovább",'hu'),
("továbbá",'hu'),
("több",'hu'),
("úgy",'hu'),
("ugyanis",'hu'),
("új",'hu'),
("újabb",'hu'),
("újra",'hu'),
("után",'hu'),
("utána",'hu'),
("utolsó",'hu'),
("vagy",'hu'),
("vagyis",'hu'),
("valaki",'hu'),
("valami",'hu'),
("valamint",'hu'),
("való",'hu'),
("vagyok",'hu'),
("van",'hu'),
("vannak",'hu'),
("volt",'hu'),
("voltam",'hu'),
("voltak",'hu'),
("voltunk",'hu'),
("vissza",'hu'),
("vele",'hu'),
("viszont",'hu'),
("volna",'hu');
